### ISSUE TITLE
Config Server Health Status

### ISSUE THREAD

**Issue by ccit-spence** [spring-cloud/spring-cloud-config#104]
Everything on the config server is working.  Clients work etc...   When I pull the health it is showing `DOWN`.  Do I need to do something else to make it work?

```
"configServer": {
"status": "DOWN",
"error": "no property sources located"
},
```

This is in the `application.yml`

```
endpoints:
    restart:
        enabled: true
    shutdown:
        enabled: true
    health:
        enabled: true
        sensitive: false
```
