### ISSUE TITLE
List handling in Spring Cloud Config

### ISSUE THREAD

**Issue by jhiemer** [spring-cloud/spring-cloud-config#1058]
Hi,
I was playing around a bit with Lists in Spring Cloud Config. What I tried was the following scenario:

My YAML file contains the following properties:
```yaml 
site:
  properties:
    section1:
      server_ips1:
      - 10.0.8.12
      - 10.0.16.11
      server_ips2:
      - 10.0.16.12
      - 10.0.8.13
```
As the properties per `site` heavily depend on the application the `SiteConfiguration.java` property mapper looks as follows:
```java
@Configuration
@ConfigurationProperties(prefix = "site")
@Conditional(SiteConfigurationCondition.class)
public class SiteConfiguration {

    Map<String, Object> properties;

    public Map<String, Object> getProperties() {
        return properties;
    }

    public void setProperties(Map<String, Object> properties) {
        this.properties = properties;
    }
}
```

As you can see, `properties` is a `Map<String, Object`. During the parse operation I would expect to receive the following structure, containing a List as Type for `server_ips1` and `server_ips2`. What I do get instead, is a `LinkedHashMap` with a key value setup of `0:10.0.8.12` etc. 

Is this intended behaviour? If so, are there any possible workarounds?

Spring Boot: 1.5.10
Spring Cloud: Edgware.SR2
