### ISSUE TITLE
Ignoring MetadataMap.ConfigPath in Applicationserver

### ISSUE THREAD

**Issue by trickert76** [spring-cloud/spring-cloud-config#1070]
I need a Eureka/Cloud Config service running in an ApplicationServer. In a Wildfly for example, the application isn't on ROOT, but under /eureka-ds.

So I configured jboss-web.xml (context-root).
The application.yml contains

```
spring:
    application:
        name: eureka-discovery-service
    security:
        user:
            password: software1
    cloud:
        config:
            server:
                bootstrap: true
                prefix: /config
        
eureka:
....
    instance:
        metadataMap:
            configPath: /eureka-ds/config
    client:
        serviceUrl:
            defaultZone: https://user:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka-ds/eureka
```

This service comes up and registers itself to the Discovery service. The Eureka server returns via /eureka-ds/eureka/apps the service. A client, which uses bootstrap.yml to get the information stops, because the created path (based on the delivered information from the discovery service is: http://localhost/${spring.cloud.config.server.prefix}/. This would be ok, if we are in a embedded environment with a ROOT.war, but we use a "prefix". I thought, eureka.instance.metadataMap.configPath is the correct way to override the property spring.cloud.config.server.prefix,

But neither setting this value in the client (bootstrap) nor setting the value in the server (application) has any effect. The server returns /config/, but it should be /eureka-ds/config. The client only tries to reach the /config/ value (which results in a 404). I'm getting a result, when I use the correct value of http://localhost/eureka/config/name...
