### ISSUE TITLE
Vault Trust certificate not found

### ISSUE THREAD

**Issue by jeusdi** [spring-cloud/spring-cloud-config#1083]
I'm getting this message when I'm trying to make a request config server:

```
$ curl -X GET http://localhost:8888/configclient/default -H "X-Config-Token:6bd72786-5b9c-a190-aac8-7ab5f16d3f28"

{"timestamp":"2018-07-11T12:24:00.661+0000","status":500,"error":"Internal Server Error","message":"I/O error on GET request for \"https://vault.ra-sec.svc:443/v1/secret/configclient\": java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty; nested exception is javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty","path":"/configclient/default"}%
```

I've set up these lines into bootstrap.yml:

    server.ssl.trust-store: file:keystore.jks
    server.ssl.trust-store-password: secret

Any ideas?

**Comment by spencergibb** [comment]
Server SSL properties are for the server itself, not any client making connections to another server

**Comment by jeusdi** [comment]
So, which properties do I need to set up in order to avoid this exception?

**Comment by jeusdi** [comment]
I've configured cloud config server in order to be able to dispatch configs from vault:

```
spring:
  application:
    name: configserver

  profiles:
    active: vault

  cloud:
    config:
      server:
        vault:
          host: ${vault_server_host:localhost}
          port: ${vault_server_port:8200}
          scheme: ${vault_server_scheme:https}
```
So, in order to check whether cloud config server is working right, I make an http request to cloud config server using `curl` command:

    $ curl -X GET http://localhost:8888/configclient/default -H "X-Config-Token:6bd72786-5b9c-a190-aac8-7ab5f16d3f28"

I guess the problem issues from cloud config server when it tries to make the request to Vault, doesn't it?

The message come from cloud config server. It's not an issue related with `curl` client.
