### ISSUE TITLE
Keys to sanitize with native profile does not works 

### ISSUE THREAD

**Issue by Junior-Sousa** [spring-cloud/spring-cloud-config#1129]
Hi,

After setting native profile for spring cloud config server and later access an URL from one of services configuration available in config server its possible see that feature to sanitize passwords with ***** does not works.

I'm using spring cloud Finchley.SR1 with sprint boot 2.0.4.RELEASE, and I did the following configuration:

**bootstrap.yml**

```
spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        native:
          searchLocations: classpath:/config
          addLabelLocations: false
          
management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: env
        
endpoints:
  env:
    keys-to-sanitize: password   
  configprops:
    keys-to-sanitize: password
  
password: teste
```
**product-service.yml**

```
maturity:
  date: 2020/07/22
  
password: '{cipher}c1335eb9ad1fa7f37033050bebceb725cd5cc25e30f3243ebebbec7cf6476012'
```
As you can see I have specified a password at bootstrap.yml, and this password was sanitezed, I have validate by using of url: http://localhost:8888/env, but when I access http://localhost:8888/product-service/default the password from product-service.yml file that is stored at config folder is not sanitezed with characters *******
