### ISSUE TITLE
Cannot enable native repository alongside other repositories

### ISSUE THREAD

**Issue by ammmze** [spring-cloud/spring-cloud-config#1143]
Currently the `NativeRepositoryConfiguration` is annotated with [`@ConditionalOnMissingBean(EnvironmentRepository.class)`](https://github.com/spring-cloud/spring-cloud-config/blob/fdf72039af54b25ba1ecbb1cd02053b1e3cc1450/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/EnvironmentRepositoryConfiguration.java#L214), which causes it to not activate even when specified in the profiles. Am I missing something? Is this expected?

For example, here is my configuration:

```yaml
spring:
  profiles:
    active: native, vault
  cloud:
    config:
      server:
        vault:
          order: 1
          host: localhost
          port: 8200
          kv-version: 2
          profile-separator: /
        native:
          order: 2

```

One quick workaround was to add the following in my `Application.java` (of course could be anywhere under my `Application` package)...

```java
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.cloud.config.server.environment.EnvironmentRepository;
import org.springframework.cloud.config.server.environment.NativeEnvironmentProperties;
import org.springframework.cloud.config.server.environment.NativeEnvironmentRepository;
import org.springframework.cloud.config.server.environment.NativeEnvironmentRepositoryFactory;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;

// ...

/**
 * This allows us to enable the native environment repository (i.e. local files) along with another repository (i.e. git, vault, etc)
 * Currently this is not possible because the org.springframework.cloud.config.server.config.NativeRepositoryConfiguration class
 * is annotated with `@ConditionalOnMissingBean(EnvironmentRepository.class)`, so as soon as you enable another repository,
 * the native repository is no long able to be enabled.
 */
@Configuration
@ConditionalOnMissingBean(name = "nativeEnvironmentRepository", value = EnvironmentRepository.class)
@Profile("native")
class NativeRepositoryConfiguration {

	@Bean
	public NativeEnvironmentRepository nativeEnvironmentRepository(NativeEnvironmentRepositoryFactory factory,
			NativeEnvironmentProperties environmentProperties) {
		return factory.build(environmentProperties);
	}
}

```
