### ISSUE TITLE
How to load additional shared properties file?

### ISSUE THREAD

**Issue by marnee01** [spring-cloud/spring-cloud-config#1157]
How can I include a completely separate properties file that will be shared between apps, when it can't be in application.properties.

So, we have groups of applications that will share properties using an application.properties.  But we then want one set of properties to be shared by all those groups.  So, we need an extra file.

We have a single git repository that will have the following file hierarchy:

```
.repo root
     + fancyNewService1
              fancyNewService1-default.properties
              fancyNewService1-dev.properties
              fancyNewService1-prd.properties
     + fancyNewService2
              fancyNewService2-default.properties
              fancyNewService2-dev.properties
              fancyNewService2-prd.properties
     + oldIckyService
              application-default.properties
              application-dev.properties
              application-prd.properties
              + oldService1
                    oldService1-default.properties
                    oldService1-dev.properties
                    oldService1-prd.properties
              + oldService2
                    oldService2-default.properties
                    oldService2-dev.properties
                    oldService2-prd.properties
```

Our spring config service will have a bootstrap.yml file as follows:

```

spring:
  application:
    name: configservice
  cloud:
    config:
      server:
        git:
          uri: ssh://git@bitbucket.pearson.com/sharedRepo/applicationconfigurations.git
          # The following allows for finding the 'fancyNewService' apps
          searchPaths: '{application}'
          repos:
            Services:
              pattern: oldService1, oldService2
              searchPaths: 'oldIckyService/, oldIckyService/{application}'
              uri: ssh://git@bitbucket.pearson.com/sharedRepo/applicationconfigurations.git
```
For the properties under the "oldIckyService" folder, the client side is not a spring app (and not a web service).  We will specify the spring config properties via VM options, not that it really matters.  But we are specifying it like:

```
-Dspring.profiles.active=dev,default
-Dspring.cloud.config.name=oldService1

```
The oldService1 will retrieve the property sources:

oldService1-default.properties
application-default.properties
oldService1-st1.properties
application-st1.properties

The oldService2 will also receive a similar list.  And thus, oldService1 and oldService2 will share the application.property files  between them.  That application.property file should not be shared by any app outside of the old service parent folder.  So far, so good.  The above is what is working for me.

(Note: The above precedence order is not what I would expect, but I'll post that in a different issue log.) 

The question I have is about wanting another shared file that can be shared by oldService and fancyNewService.  So, how can I share the application-messaging.properties files shown below in the fancyNewServices and the oldServices?  I don't care what the files are called, fyi.  (I don't care if it has the "application" prefix or not.)

```
.repo root
     + config
               + shared
                         +messaging
                                   application-messaging.properties
                                   application-messaging-dev.properties
                                   application-messaging-prd.properties
     + fancyNewService1
     + fancyNewService2
     + oldIckyService
              + oldService1
              + oldService2
```
In the server bootstrap, I added the new folder (config/shared/messaging/) to the searchPaths for the the repos:
```

uri: ssh://git@bitbucket.pearson.com/sharedRepo/applicationconfigurations.git
          searchPaths: '{application}'
          repos:
            OldServices:
              pattern: oldService1, oldService2, messaging
              searchPaths: 'oldIckyService/, oldIckyService/{application}, config/shared/messaging/'
              uri: ssh://git@bitbucket.pearson.com/sharedRepo/applicationconfigurations.git
```

I tried the following on the client side:

- Add to the active profiles: -Dspring.profiles.active=dev,default,messaging
- Add to the name: -Dspring.cloud.config.name=oldService1,messaging

Neither worked. 

Adding to profiles doesn't work, because I also need to apply profiles on the application-messaging file itself, and it always just gives me:

    application-msg.properties
never: 
    application-msg-**dev**.properties

When I specify it instead on "name" instead of "profiles.active", then **no** property sources are returned at all.  It does not like multiple names.
