### ISSUE TITLE
Property sources returned in wrong order and in a Collection (precedence order is wrong)

### ISSUE THREAD

**Issue by marnee01** [spring-cloud/spring-cloud-config#1158]
**Defect Summary**: The precedence of property sources returned by spring config server puts application.properties as higher precedence than app-specific properties file.  Therefore, when one is using application.properties to share common configs between apps, one can never override something in application.properties for a specific application.

**Details:**

So, we have groups of applications that will share properties using an application.properties.

We have a single git repository that will have the following file hierarchy:

```
.repo root
     + services
              application-default.properties
              application-dev.properties
              application-prd.properties
              + service1
                    service1-default.properties
                    service1-dev.properties
                    service1-prd.properties
              + service2
                    service2-default.properties
                    service2-dev.properties
                    service2-prd.properties
```

Our spring config service will have a bootstrap.yml file as follows:

```

spring:
  application:
    name: configservice
  cloud:
    config:
      server:
        git:
          uri: ssh://git@bitbucket.pearson.com/sharedRepo/applicationconfigurations.git
          # The following is not relevant for this particular issue, but it is what we do have in our file.
          searchPaths: '{application}'
          repos:
            Services:
              pattern: service1, service2
              searchPaths: 'service/, service/{application}'
              uri: ssh://git@bitbucket.pearson.com/sharedRepo/applicationconfigurations.git
```
For the properties under the "service" folder, the client side is not a spring app (and not a web service).  We will specify the spring config properties via VM options, not that it really matters.  But we are specifying it like:

```
-Dspring.profiles.active=dev,default
-Dspring.cloud.config.name=service1

```
We have to implement client-side code to read these property sources and produce a properties map.

Sample code:
```


final CompositePropertySource compositePropertySource 
    = (CompositePropertySource)environment.getPropertySources().get("configService");

if (compositePropertySource != null) {
    if (compositePropertySource.getPropertySources() != null) {
					
        for (final Object mapPropertySourceObject : compositePropertySource.getPropertySources()) {
            final MapPropertySource propertySource = (MapPropertySource)mapPropertySourceObject;

            if (propertySource != null) {
                p.putAll(propertySource.getSource());
            }
        }
    }
}

```

There are two related problems.

1) The first is that the CompositePropertySource.getPropertySources() returns a **Collection**, even though it stores the property sources internally in a LinkedHashSet.  That means that to the caller of that method, there is **no** order to the property sources (even though in the current implementation of CompositePropertySource it does maintain an order internally.  And there is no other method that allows for explicitly testing the precedence of a given property source.

2) The big issue is that the order they are returned can not be correct.  For service1, the property sources are in the following order.
...
service1-default.properties
**application**-default.properties
service1-dev.properties
**application**-dev.properties
...

The last one wins, which means that application-default.properties overrides service1-default.properties.

That makes no sense and can not be what was intended.

If we have:

application-default.properties:
`securityCheckLoggingInterval=120`

service1-default.properties:
`securityCheckLoggingInterval=60`

service3-default.properties:
`securityCheckLoggingInterval=20`

Then I expect the value will be:
service1:  60
service2: 120 (default)
service3: 20
service4: 120 (default)
service5: 120 (default)
service6: 120 (default)

But instead, application.properties takes precedence, so the value will be 120 for **all** the services.  Therefore, there is actually no way to override a shared value.  Instead, if the shared value must differ for one app, you simply can't put it in application.properties. You have to copy the property into each and every service*-default.properties file, with most of the values being the same.

Note that we have dozens of these old services.  And we have 9 different environments (so 9 different profiles).  It is imperative that we be able to share properties, but also be able to override when needed.

Is this just a configuration issue on my part, or is it a defect in spring config server?  (It can't be the expected behavior.)
