### ISSUE TITLE
Pure wildcard patterns break searches across multiple repositories

### ISSUE THREAD

**Issue by alexcorvino** [spring-cloud/spring-cloud-config#117]
I've set up multiple repositories with configuration in each.

common repo contains:
common-dev.yml
common-qa.yml
common-mysql.yml

foo-config repo contains:
foo-dev.yml
foo-qa.yml

bar-config repo contains:
bar-dev.yml
bar-qa.yml

I've configured my Spring Cloud Config Server like so:

```
git:
    uri: ssh://git@stash:7999/scc/common.git
    repos:
        foo-config:
            uri: ssh://git@prod-app1000.idanalytics.com:7999/scc/foo-config.git
            pattern: "*"
        bar-config:
            uri: ssh://git@prod-app1000.idanalytics.com:7999/scc/bar-config.git
            pattern: "*"
```

Issuing a curl command against foo/dev or foo/qa will return configuration in propertySources. Issuing a curl command against bar or common will return empty propertySources.
