### ISSUE TITLE
Spring Cloud Config Git Basedir

### ISSUE THREAD

**Issue by eevariste** [spring-cloud/spring-cloud-config#1175]
I am testing out spring-cloud-config-server and getting an odd situation where repo directories are not created as expected.

Setting spring.cloud.config.server.git.basedir to a given path doesn't create config-repo-* directories below that path. E.g.

```
spring:
      cloud:
          config:
              server:
                  git:
                      basedir: "/config-server/repos"
```

The above will be created but the repo directories will be stored in /config-server instead of /config-server/repos I am using 2.0.2.RELEASE of spring-cloud-config-server.

**Comment by eevariste** [comment]
@ryanjbaxter As a test I set the basedir to "/var/tmp/spring-cloud/repos/" without creating the repos directory. After querying the server these are the folders under /var/tmp/spring-cloud.

```
Nov  5 14:05 config-repo-8260599878887614334
Nov  5 14:04 repos
```

I would expect config-repo-8260599878887614334 to be below repos.

**Comment by ryanjbaxter** [comment]
Can you provide a project to reproduce it?  I am not seeing the problem locally.

**Comment by eevariste** [comment]
@ryanjbaxter The project is here https://github.com/eevariste/config-server.git. I ran a few more tests and the issue seems to be related with place holders in the git uri. With a setup like this

```
spring:
   cloud:
       config:
           server:
               git:
                   basedir: "/var/tmp/spring-cloud/repos/"
                   uri: https://github.com/eevariste/config-repo
```

I can see the .properties files below /var/tmp/spring-cloud/repos/.

The following setup gives the result mentioned at the beginning.
```
spring:
   cloud:
       config:
           server:
               git:
                   basedir: "/var/tmp/spring-cloud/repos/"
                   uri: https://github.com/eevariste/{application}
```
