### ISSUE TITLE
config pattern priority

### ISSUE THREAD

**Issue by linjisong** [spring-cloud/spring-cloud-config#1212]
In my project, the following is configured
```yml
spring:
  profiles: git
  cloud:
    config:
      server:
        default-label: master
        git:
          uri: https://github.com/smartapi-cloud-config-repo.git
          repos:
            smartapi-cloud-demo:
              pattern: smartapi-cloud-demo-*
              uri: https://github.com/smartapi-cloud-config-demo.git
            smartapi-cloud:
              pattern: smartapi-cloud-*
              uri: https://github.com/smartapi-cloud-config.git
```
I want `smartapi-cloud-demo-base` to visit `https://github.com/smartapi-cloud-config-demo.git`, but actually access `https://github.com/smartapi-cloud-config.git`, here Pattern matching has no priority?
