### ISSUE TITLE
Ordering of mutliple Git repos

### ISSUE THREAD

**Issue by brianjones** [spring-cloud/spring-cloud-config#1218]
The Config Server used to honor the ordering of mulitple Git repositories, but that no longer happens.

For example, if the configration is:
```
spring:
  cloud:
    config:
      server:
        git:
          repos:
            production:
              pattern:
              - '*/production'
              uri: https://internal-git-repo/production.git
              pattern:
              - '*/production*'
              uri: https://internal-git-repo/production-copy.git
```

and you make a call to get configuration for "testapp" with an active spring profile of "production", you may get either the first or second repo.

The `MultipleJGitEnvironmentProperties` class explicilty uses a LinkedHashMap to maintain order, but the  `MultipleJGitEnvironmentRepository` converts this to a HashMap, losing the ordering.

This was broken with b96ba4454d9517ab2c49fe0e9a3d033e396c0f69.

The problematic line of code is in the constructor:
```
		this.repos = properties.getRepos().entrySet().stream()
				.map(e -> new AbstractMap.SimpleEntry<>(e.getKey(),
						new PatternMatchingJGitEnvironmentRepository(environment, e.getValue())))
				.collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
```

as `Collectors.toMap` creates a HashMap by default.

Could this be changed to:
```
		this.repos = new LinkedHashMap<>();
		for (Map.Entry entry : properties.getRepos().entrySet()) {
			repos.put(entry.getKey(), new PatternMatchingJGitEnvironmentRepository(environment, e.getValue()));
		}
```

or, if to stick with the streaming API, something like:

```
		this.repos = properties.getRepos().entrySet().stream()
				.map(e -> new AbstractMap.SimpleEntry<>(e.getKey(),
						new PatternMatchingJGitEnvironmentRepository(environment, e.getValue())))
				.collect(
					LinkedHashMap::new,
					(map, entry) -> map.put(entry.getKey(), entry.getValue(),
					Map::putAll);

```
