### ISSUE TITLE
How to define a partial searchPath and share it between remote repo definitions?

### ISSUE THREAD

**Issue by marnee01** [spring-cloud/spring-cloud-config#1225]
When using git as the repo, is there a way to define a search path that is used for all searches in addition to the explicit one set for a given repo definition?

For example, let's say we have this:
```

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri : ssh://git@bitbucket.pearson.com/blahblah/OurProperties.git
          repos:
            AppCategory1:
              pattern: Service1
              searchPaths: 'Services/{application}, Common/Module1, Common/Module2'
            HubWrapper:
              pattern: App1
              searchPaths: 'Applications/{application}, Common/Module1, Common/Module2'

```
Assume that we can not combine the searchPaths (due to global variables under Services and Applications folders that shouldn't be shared between the two, for example).

Is there a way to define "Common/Module1, Common/Module2" as some kind of variable and then reference that in searchPaths so we don't have to duplicate it? Or, is there any other way that we don't have to duplicate it?

**Comment by ryanjbaxter** [comment]
Not that I know of.  how many `searchPaths` are there in your use case and is each value completely different?

**Comment by marnee01** [comment]
We have repo definitions that each have a searchPath that includes three definitions similar to this:

`Common/MessengerService, Common/MessengerService/*, Common/MessengerService/SharedDomains/*`

It would be nice (but isn't mandatory) that we could define that just once. It would be more readable. If there isn't a way, this isn't an issue, but could be converted to enhancement request.

**Comment by ryanjbaxter** [comment]
In the example above the `searchPaths` are slightly different, only a portion of them are the same.  I was wondering if that is the case for all repos?  (ie each `searchPath` is only slightly different)

**Comment by marnee01** [comment]
That is correct. (Only a portion of them are the same and that is the case for all repos. All repos three identical folder paths, and in addition they each have one or more path that is unique to that repo searchPath.)

**Comment by spencergibb** [comment]
Have you tried using using [placeholders](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-placeholders-in-properties).

```
common:
  search-path: Common/MessengerService, Common/MessengerService/*, Common/MessengerService/SharedDomains/*

#322 
    search-paths: Custom, ${common.search-path}
```
