### ISSUE TITLE
Spring Cloud Config with Eureka - contextPath

### ISSUE THREAD

**Issue by leebake** [spring-cloud/spring-cloud-config#1242]
I have a problem with discovery config-server via Eureka. My apps are deployed on WebLogic server with contextPath given in  wls:context-root.

1. Config server

```
contextRoot: /config-server
```
application.yml
```
server:
  port: 7001

context-path: config-server

eureka:
  instance:
    status-page-url-path: ${context-path}/info
    health-check-url-path: ${context-path}/health
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/service-registry/eureka/
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: URL TO REPO
```

2. Eureka
```
contextRoot: /service-registry
```
bootstrap.yml
```
server:
  port: 7001
spring:
  cloud:
    config:
      name: discovery
      uri: http://localhost:7001/config-server/
```
3. MS1
```
contextRoot: /ms1
```
bootstrap.yml
```
spring:
  cloud:
    config:
      name: message-store
      discovery:
        enabled: true
      fail-fast: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/service-registry/eureka/
```

The MS1 can't get config from config-server because it send a request to localhost:7001 - wthout contextPath. That's the address MS1 (I suppose) gets from Eureka. Why Eureka dont't return url with contextPath? Config server has been registered with both status-page-url-path and health-check-url-path contains contextPath.
