### ISSUE TITLE
/shutdown endpoint doesn't exit the process when using spring.cloud.config.discovery.service-id

### ISSUE THREAD

**Issue by tuhao1020** [spring-cloud/spring-cloud-config#1339]
I just create a simple project using Spring Boot 2.1.3.RELEASE, and add some dependencies such as spring-boot-starter-web, spring-cloud-starter-config, spring-boot-starter-actuator and spring-cloud-starter-consul-discovery.

my bootstrap.yml is as below:
```
server:
  port: 8800

spring:
  application:
    name: test-demo
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        prefer-ip-address: true
    config:
      discovery:
        service-id: config-server
        enabled: true
      fail-fast: true

management:
  endpoints:
    web:
      base-path: /mnt
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
```
When I send a post request to http://localhost:8800/mnt/shutdown, the process doesn't quit, but it works when I replace the spring.cloud.config.discovery.service-id with uri:
```
config:
  uri: http://localhost:8718
```
