### ISSUE TITLE
Native environment not loaded with custom environment repository

### ISSUE THREAD

**Issue by komoo1** [spring-cloud/spring-cloud-config#1344]
Given the spring cloud implementation below, only properties from the custom repository implementation are loaded to the config client.

Only test.key property from the custom repository is available for the config clients.

Spring cloud - Greenwich-RELEASE
Spring boot - 2.1.2-RELEASE

### Config server application.yml
```
server:
    port: 8888
spring:
    cloud:
        config:
            server:
                accept-empty: false
                native:
                    search-locations: classpath:/config
                    addLabelLocations: false
                    fail-on-error: true
                    order: 1
    profiles:
        active: native
```

### Custom repository bean implementation

```
public class CustomEnvironmentRepository implements EnvironmentRepository, Ordered {

    @Override
    public Environment findOne(String application, String profile, String label) {
        String[] profiles = StringUtils.commaDelimitedListToStringArray(profile);
        Environment environment = new Environment(application,  profiles);

        Properties props = new Properties();
        props.setProperty("test.key", "value");

        environment.add(new PropertySource("application-dev", props));

        return environment;
    }

    @Override
    public int getOrder() {
        return Ordered.LOWEST_PRECEDENCE;
    }
}
```

#### The Workaround
Using a local git repository with 'basedir' and the custom repository implementation works fine and serves intended purpose to have config properties for all client applications in a single folder location and have a custom repository that loads and serves config properties from a SQL based datasource

 See related [StackOverflow issue](https://stackoverflow.com/questions/51063714/spring-cloud-config-composite-repositories) also. 

Using a composite environment did not solve this either. Please advise if this is a non-issue and recommend an appropriate configuration for native+custom environment repositories.
