### ISSUE TITLE
is there anyway to share some ssh public key from multiple git repository ?

### ISSUE THREAD

**Issue by Incarnation-p-lee** [spring-cloud/spring-cloud-config#1345]
As I know, cloud config server support one default git repo and repos with pattern as below:

```yaml
spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:spring-cloud-samples/config-repo
          repos:
            simple: git@github.com:simple/config-repo
            special:
              pattern: special*/dev*,*special*/dev*
              uri: git@github.com:special/config-repo
```

So there is one question here, if all above git url is ssh authorized, is there any way to share the same ssh public key as the deploy key ? I did some investigation about this limitation:

* For now by default, config server only take default ssh key name like `id_rsa` and `id_rsa.pub`.
* Github do not allow share ssh public key between different repos, or you may get `This key is in use already`.

Any idea about this issue ?
