### ISSUE TITLE
No active profile set, falling back to default profiles: default

### ISSUE THREAD

**Issue by liuyang2010001256** [spring-cloud/spring-cloud-config#1346]
my application run with this error, and when i change config file's name from application-dev.yml to application-ops.yml and change application.yml's active from dev to ops. it run successful,i want to know why?
my config:
```
server.port: 8088
management.port: 9988



spring:
  application:
    name: xxx
  cloud:
    consul:
      enabled: false
      discovery:
        fail-fast: false

management:
  security:
    enabled: false

abc:
  web:
    xxljob:
      enabled: true
      admin:
        addresses: xxx
      executor:
        appname: cmdb
        ip:
        port: 9998
        accessToken: 53aa095311
        logpath: D:\download
        logretentiondays: -1

  data:
      pagehelper:
        helperDialect: mysql
        reasonable: true
        supportMethodsArguments: true
        params: count=countSql
      mybatis:
        typeAliasesPackage: com.xx.devops.xx.business.entity
        mapperLocations:
           classpath: com/xx/devops/xx/fetcher/cmdb/repo/xml/*.xml
      mapper:
        notEmpty: true
      database:
        primary: master
        connection:
          master:
            type: com.zaxxer.hikari.HikariDataSource
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://xx/mysql?useSSL=false&characterEncoding=UTF-8
            username: root
            password: xx
            hikari:
              auto-commit: true
              connection-timeout: 10000
              idle-timeout: 600000
              max-lifetime: 1800000
              minimum-idle: 10
              maximum-pool-size: 10


cmdb.url: xx
cmdb.params: cmdb/params
cmdb.headers: cmdb/headers
```
(please ignore xx)
