### ISSUE TITLE
ConfigClientWatcher with Git backend

### ISSUE THREAD

**Issue by dlsrb6342** [spring-cloud/spring-cloud-config#1378]
With git backend, as I know, Environment.getVersion() return HEAD Commit's checksum.
But ConfigClientWatcher just watch "config.client.state" value.

If ConfigClientWatcher watch "config.client.version", It would be works well with git without any config.
How do you think about this? I would like to make a implementation based on this.

**Comment by ryanjbaxter** [comment]
What problem are you running into with the current implementation?
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by dlsrb6342** [comment]
It doesn't have any other config or code. I just run one spring-cloud-config-server and one client.
my client project's bootstrap.yml 
```
spring:
  application:
    name: client
  profiles:
    active: local

  cloud:
    config:
      uri: http://localhost:8081
      fail-fast: true
      watch:
        enabled: true
```

and my server project's application.yml
```
server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dlsrb6342/configs.git
          clone-on-start: true
          username: USERNAME
          password: PASSWORD
```

spring.cloud.config.watch.enabled is set true for ConfigClientWatch.
ConfigClientWatch check state by below code.
```
String newState = this.environment.getProperty("config.client.state");
String oldState = ConfigClientStateHolder.getState();
```

With github as backend, spring-cloud-config-server doesn't send state. 
Because of this, newState and oldState are always NULL. so it never refresh.

But cloud-config-server with github, it send **version**.
**version** means git HEAD commit's checksum. So I can recognize whether the config repo is updated by compare newVersion and oldVersion.

So I think ClientConfigWatch should be watching **version**.
