### ISSUE TITLE
Only application.yml is retrieved when using "organization" notation

### ISSUE THREAD

**Issue by daniel-alonso-sanchez** [spring-cloud/spring-cloud-config#1387]
**Issue:**

I'm trying to use the "organization" notation defined here 

https://cloud.spring.io/spring-cloud-config/multi/multi__spring_cloud_config_server.html

For instance: 

http://localhost:8888/level1(_)level2(_)sboot-configs(_)prueba1/int

Against a git server with the following files:

- application.yml
- prueba1-int.yml	
- prueba1.yml

Everything looks fine until the response is returned:

```
{
    "name": "level1/level2/sboot-configs/prueba1",
    "profiles": [
        "int"
    ],
    "label": null,
    "version": "60ad6d2d4d4f150a04e34589116891c9d53a323b",
    "state": null,
    "propertySources": [
        {
            "name": "https://myserver:myport/level1/level2/sboot-configs/prueba1-config.git/application.yml",
            "source": {
                "propiedad-generica": "valor_generico"
            }
        }
    ]
}
```

If I don't use the "organization" notation, and change configuration in order to point to the repo, it retrieves the three files...

I have noticed that the class NativeEnvironmentRepository has a method getArgs, The _application_ parameter has the value level1/level2/sboot-configs/prueba1 .

Do you know how can i solve this in order to use the organization notation?

Thanks a lot in advance. 

Kind Regards

**Comment by Haybu** [comment]
would you please paste your config server configuration (formatted please).

**Comment by daniel-alonso-sanchez** [comment]
Hi Haybt,

Sure. Here it is:

```
spring:  
  cloud:
    config:
      server:
        git:
          uri: https://corporate-gitlab/{application}-config.git
          username: user
          password: pass
          skip-ssl-validation: true         
          repos:
              no-prod:
                 pattern:
                   - '*/int'
                   - '*/test'
                 uri: https://corporate-gitlab/{application}-config.git
                 username: user
                 password: pass         
                 skip-ssl-validation: true
              prod:
                 pattern:
                   - '*/prod'
                 uri: https://corporate-gitlab/sboot-configs/prod-configs.git
                 username: user
                 password: pass         
                 skip-ssl-validation: true
                 search-paths: apps
```

I'm using latest spring relase (2.1.5 and  Greenwich.SR1)

Thanks a lot in advance!
