### ISSUE TITLE
Client uses active profiles as labels when fetching

### ISSUE THREAD

**Issue by bjoernmayer** [spring-cloud/spring-cloud-config#1409]
Hi,

my config server is file based an the structure looks like this:
- application.yml (settings for every application)
- application-mysql.yml (mysql specific stuff)
- application-grpc.yml (grpc specific stuff)

In the client my bootstrap.yml looks like this:
```yaml
spring:
  application:
    name: 'accommodation-review'
  cloud:
    config:
      uri:  http://localhost:8888/config # When creating this issue /config was missing from this line
  profiles:
    active:
      - mysql
      - grpc
```

Booting up the client fails, because no configurations for mysql or grpc could be found.
In the output I see this:

`.c.c.ConfigServicePropertySourceLocator : Located environment: name=config, profiles=[accommodation-review], label=mysql,grpc, version=null, state=null`

As you can see the profile is the application name. The active profiles are used as labels.

The application worked fine, when I changed my bootstrap.yml to:
```yaml
spring:
  application:
    name: 'accommodation-review'
  cloud:
    config:
      name: mysql,grpc # this is where the profiles go
      uri:  http://localhost:8888/config
```

Output:
`c.c.c.ConfigServicePropertySourceLocator : Located environment: name=config, profiles=[mysql,grpc], label=default, version=null, state=null`

Am I doing something wrong?

Versions:
`spring-cloud-config-server: 2.1.2.RELEASE`
`spring-cloud-starter-config 2.1.2.RELEASE`
