### ISSUE TITLE
Config server doesn't preserve quotes when resolving placeholders

### ISSUE THREAD

**Issue by tnaskali** [spring-cloud/spring-cloud-config#1413]
In Spring Cloud config v.1.4.3.RELEASE (not tested with more recent versions), if a YAML property value is quoted and referenced through a placeholder, the quotes are not preserved after the config server performs placeholders resolution.
For example
```yaml
key1:
  key11: 'value1:'
  key12: ${key1.key11}
```
becomes after resolution
```yaml
key1:
  key11: 'value1:'
  key12: value1:
```
while you would expect
```yaml
key1:
  key11: 'value1:'
  key12: 'value1:'
```
