### ISSUE TITLE
The plain YAML array wrapped with a "document" element

### ISSUE THREAD

**Issue by alexterman** [spring-cloud/spring-cloud-config#143]
When fetching YAML array from the server , it adds "document" element , which wraps the data.

The originally stored data:
```
---  
- 
  id: "124"
  name: "name1"
- 
  id: "125"
  name: "name2"

```

The returned data:
```
document:
- 
  id: "124"
  name: "name1"
- 
  id: "125"
  name: "name2"
```

Is it expected behavior?
Is it possible to get the data without "document" level (just as it)?
