### ISSUE TITLE
List properties from multiple files

### ISSUE THREAD

**Issue by dlsrb6342** [spring-cloud/spring-cloud-config#1430]
I want to use multiple files and list properties.
If I add a list properties on multiple file, it will be overridden another one. 

```yml
# application.yml
test:
  properties:
    - foo1
    - foo2 
    - foo3

# application-local.yml
test:
  properties:
    - bar1
    - bar2
```
I wanna get ["foo1", "foo2", "foo3", "bar1", "bar2"]. But I got ["bar1", "bar2", "foo3"].
Is there any way concat list properties not override?
