### ISSUE TITLE
Ciphered values in YAML should be quoted?

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-config#144]
Again maybe I misunderstood sth but when taking a look at the documentation (http://projects.spring.io/spring-cloud/spring-cloud.html#_spring_cloud_config) with such a snippet:

```
spring:
  datasource:
    username: dbuser
    password: {cipher}FKSAJDFGYOS8F7GLHAKERGFHLSAJ
```

I got an exception during YAML parsing that "{" was unexpected. Only after writing

```
spring:
  datasource:
    username: dbuser
    password: '{cipher}FKSAJDFGYOS8F7GLHAKERGFHLSAJ'
```

did I manage to have it done properly. Have I done sth wrong or is there a bug in the doc?
