### ISSUE TITLE
Error: "More than one git repo URL template matched URL"

### ISSUE THREAD

**Issue by marnee01** [spring-cloud/spring-cloud-config#1480]
We recently tried to upgrade from Edgware.SR5 to Greenwich SR3. ConfigServer reports the following error for certain requests:

> More than one git repo URL template matched URL

The error is coming from the `HttpClientConfigurableHttpConnectionFactory.lookupHttpClientBuilder` method. With Greenwich SR3, a [bugfix](https://github.com/spring-cloud/spring-cloud-config/pull/1429) was implemented in that class based on a support ticket my team opened. However, it appears it was only a partial fix.

We have a bootstrap similar to this:

```
spring:
  cloud:
    config:
      server:
        git:
          uri: https://blahblah/v1/repos/vvv_configs-{application}
          proxy:
            https:
              host: ${proxyuri}
              port: '8080'

          repos:

            WebApp:
              pattern: webapp
              searchPaths: SharedDomains/*, {application}
              basedir: ${basedirParent}\\baseWebApp
              uri: https://blahblah/v1/repos/vvv_configs-webapp
              proxy:
                https:
                  host: ${proxyuri}
                  port: '8080'
```

The problem is that if you call configserver for application "webapp", the `lookupHttpClientBuilder` method finds **both** uris shown in the sample bootstrap above. The `lookupHttpClientBuilder` expected to find one and only one. The service will continue on to process the request, but logs error:

> More than one git repo URL template matched URL: https://blahblah/v1/repos/vvv_configs-webapp/info/refs?service=git-upload-pack, proxy and skipSslValidation config won't be applied. Matched templates: https://blahblah/v1/repos/vvv_configs-{application}, https://blahblah/v1/repos/vvv_configs-webapp

We need to use the proxy, so this won't work for us.

This did not happen with Finchley. (The `HttpClientConfigurableHttpConnectionFactory` class did not exist in that release.)

1) I wanted to first relay the issue and request that it be fixed.
2) Short-term, I am trying to find a workaround. I am hoping you can help. We have a strong need to upgrade to the latest release very soon.

**Workaround:**
For a workaround, I tried adding a default repo entry to the end of the bootstrap and removing the default git entry, as shown below. Unsurprisingly, the service won't even start if you don't have `spring.cloud.config.server.git.uri` defined. So this did not work:

```
spring:
  cloud:
    config:
      server:
        git:
          repos:
            WebApp:
              pattern: webapp
              searchPaths: SharedDomains/*, {application}
              uri: https://blahblah/v1/repos/vvv_configs-webapp
              proxy:
                https:
                  host: ${proxyuri}
                  port: '8080'
                  
            Default:
              pattern: '*'
              uri: https://blahblah/v1/repos/vvv_configs-{application}
              proxy:
                https:
                  host: ${proxyuri}
                  port: '8080'
```

We could add the `spring.cloud.config.server.git.uri` back in to point to just one repo instead of using {application} placeholder and have the `Default` for everything else. But for that one repo specified on `spring.cloud.config.server.git.uri`, we'll get the error, so that won't work. We could put a dummy repo in for `spring.cloud.config.server.git.uri`, but that is too much of a hack for a long-term solution.

Can you think of a way for us to configure repos so that only one repo url is ever found? Is there a way to specify the `Default` repo as in my example, but in addition to `pattern`, add an exclusion to exclude the repo present as the default? Something like the example below. In that example, note:

- The `spring.cloud.config.server.git.uri` is set to vvv_configs-**authenticationAccounts** instead of vvv_configs-**{application}**

- The `Default` repo has a `patternExclude` (which isn't a real parameter).

```
spring:
  cloud:
    config:
      server:
        git:
          uri: https://blahblah/v1/repos/vvv_configs-authenticationAccounts
          proxy:
            https:
              host: ${proxyuri}
              port: '8080'

          repos:

            WebApp:
              pattern: webapp
              searchPaths: SharedDomains/*, {application}
              uri: https://blahblah/v1/repos/vvv_configs-webapp
              proxy:
                https:
                  host: ${proxyuri}
                  port: '8080'
                  
            Default:
              pattern: '*'
              patternExclude: authenticationAccounts
              uri: https://blahblah/v1/repos/vvv_configs-{application}
              proxy:
                https:
                  host: ${proxyuri}
                  port: '8080'
```

Can `pattern` be regex, or is asterisk for wildcard the only matching that is supported?

Note that eliminating having a token in the uri (vvv_configs-{application}) and explicitly defining a repo entry for every service and app is not a feasible workaround for us. We have many dozens (100s?) of apps and services. It's not feasible to add a repo entry into the bootstrap for each of them and also have to continue adding for every new service we create.
