### ISSUE TITLE
The wrong http settings may be used if there are two git repo configs for the same url

### ISSUE THREAD

**Issue by marnee01** [spring-cloud/spring-cloud-config#1482]
While investigating issue [Error: "More than one git repo URL template matched URL"](https://github.com/spring-cloud/spring-cloud-config/issues/1480), I spotted another possible defect in the HttpClientConfigurableHttpConnectionFactory implementation.

If someone has multiple git repo configs for the same url, but with different http settings, only one of the http settings will be used, regardless of how the request coming in. 

Note: This does not impact my team, but since I spotted it, I thought I would relay this.

If someone has a configuration such as:

```
spring:
  cloud:
    config:
      server:
        git:
          uri: https://blahblah/v1/repos/vvv_configs-{application}
          proxy:
            https:
              host: ${proxyuri}
              port: '8080'

          repos:

           # No proxy in dev environment
            WebApp-Dev:
              pattern: webapp/dev
              searchPaths: SharedDomains/*, {application}
              basedir: ${basedirParent}\\baseWebApp
              uri: https://blahblah/v1/repos/vvv_configs-webapp
				  
           # Proxy needed for all environments except dev
            WebApp:
              pattern: webapp
              searchPaths: SharedDomains/*, {application}
              basedir: ${basedirParent}\\baseWebApp
              uri: https://blahblah/v1/repos/vvv_configs-webapp
              proxy:
                https:
                  host: ${proxyuri}
                  port: '8080'
```

The `HttpClientConfigurableHttpConnectionFactory.addConfiguration` method puts http clients into its internal map with the url as key. Since url is the same, that means that there will only be one entry for the vvv_configs-webapp URL in the map, even though there are two different configs for that URL. Whether the http client will be the one using the proxy or the one without is indeterminate (second one added to the map wins, obviously).

I did a quick test, and confirmed this behavior. Whether I call with "dev" profile or not, it will always use the same http client object. I am using Greenwich SR3.
