### ISSUE TITLE
Can I use the relative path for native profile? If not,How to reduce developers changing the property?

### ISSUE THREAD

**Issue by andyzhaozhao** [spring-cloud/spring-cloud-config#1504]
There is a config server project with native profile.
```
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          searchLocations: /Users/user/MSProjects/tdf-cloud-platform/tdf-config-profile/dev
```
The problem is A**fter clone the config server project from git, all the developers need to change the "searchLocations" property ,because different developers have different "searchLocations"** . I think the real problem is the "searchLocations" is a Absolute path . 

**If I can use the relative path such as “_searchLocations: "file:///../tdf-config-profile/dev"_” , All the developers have the same relative path, they will not need to change the property.**

Can I use the relative path? If not,How to reduce developers changing the property?
