### ISSUE TITLE
Spring cloud config server returning internal server error when accessed without an X-Config-Token with multiple backends

### ISSUE THREAD

**Issue by N4zroth** [spring-cloud/spring-cloud-config#1512]
**Describe the bug**
Spring-cloud version Hoxton.RC2
When accessing a cloud-config server that has vault and another (e. g. git) backend without an X-Config-Token, an internal server error is thrown because the HttpRequestConfigTokenProvider finds no token (which by itself is correct). Wouldn't it be correct to ignore backends requiring authentication and only serving backends that aren't secured? A check in CompositeEnvironmentRepository.findOne might solve this.

**Sample**
- out of the box config server with (running) vault and git backend
- client application that e. g. tries to get the logback.xml from a centralized configuration server like this (bootstrap.yml):
```
spring:
  application:
    name: discovery-service
  cloud:
    config:
      uri: http://localhost:8888
      token: myroot
  profiles:
    active: development
logging:
  config: ${spring.cloud.config.uri}/${spring.application.name}/${spring.profiles.active}/master/logback.xml
```
