### ISSUE TITLE
Spring Boot Admin or Spring Cloud Gateway could not fetch the dynamic Eureka clients when using Spring Cloud Config

### ISSUE THREAD

**Issue by andyzhaozhao** [spring-cloud/spring-cloud-config#1530]
sample: https://github.com/andyzhaozhao/spring-cloud-config-issues-1530-sample
Everything runs well in  Spring Cloud G. The problem occured after we have upgraded to H.
### version
* Spring Cloud Hoxton.SR1
* Sping Boot 2.2.1

#### run without Spring Cloud Config
Everything runs well when did not using the Spring Cloud Config.   There's a Gateway microservice named "tdf-cloud-gateway" in front of other microservices such as "tdf-service-sys","tdf-service-route" and so on. "tdf-cloud-gateway" can auto proxy the new service registered in eureka. 
1. all the microservices Cluster runs well .
1. the tdf-cloud-gateway run on port 8090, http://localhost:8090/.....
1. create new a microservice named "tdf-service-sample" and runs on port 8050.
1. "tdf-cloud-gateway" can auto proxy "tdf-service-sample" by http://localhost:8090/tdf-service-sample/...

#### the problem description when using Spring Cloud Config
then "tdf-cloud-ateway" using "tdf-cloud-config" (a Spring Cloud Config service):
```
spring:
  profiles: dev
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 2000
        max-attempts: 15
        max-interval: 3000
        multiplier: 1.3
      profile: dev
      discovery:
        enabled: true
        service-id: tdf-cloud-config
```
1. all the microservices Cluster runs well .
1. the tdf-cloud-gateway run on port 8090, http://localhost:8090/.....
1. create new a microservice named "tdf-service-sample" and runs on port 8050.
1. "tdf-cloud-gateway" **can not** auto proxy "tdf-service-sample" by http://localhost:8090/tdf-service-sample/...

#### conclusion
when using Spring Cloud Config, gateway **can not** auto proxy service added into microserice cluster dynamically . May be the problem is from Spring Cloud Config .
