### ISSUE TITLE
Zuul routing order is not preserved while fetching the routes from config server

### ISSUE THREAD

**Issue by sureshkrishnamoorthy** [spring-cloud/spring-cloud-config#1535]
We have updated our zuul service to Hoxton release recently. As per the documentation, if we use yml file for routes the order will be preserved but After the update we noticed that the zuul routing order is lost when the routes are fetched from config server but if we have the routes as part of application it is working as expected. 

For eg below is our sample routing config
```
zuul:
  routes:
    specificproduct:
      path: /v1/product/electronics/**
      service-id: electronic-product-service
      strip-prefix: false
      sensitiveHeaders:
    genericproduct:
      path: /v1/product/**
      service-id: product-service
      strip-prefix: false
      sensitiveHeaders:
```

In our case, if the routes are fetched from config server the requests are always forwarded to product-service instead of electronic-product-service even the path is /v1/product/electronics/** 
This works as expected when we have the route config as part of application and disable config server.
