### ISSUE TITLE
If the configuration center has a project name, then the configuration file will not be obtained

### ISSUE THREAD

**Issue by cielswift** [spring-cloud/spring-cloud-config#1538]
spring boot 2.2.2
```
server:
  port: 3700
  servlet:
    context-path: /config   #Here is the project root path
spring:
    cloud:
        config:........
-----------------------------------------------------------------
```
```
cloud: 
    config:
      discovery:
        service-id: springcloud-config  
        enabled: true  
      profile: dev 
      label: master 
      username: xia #bais 认证
      password: 123 #bais 认证
```

Can't get configuration ,Because there is a project root path / config
