### ISSUE TITLE
Specify bucket folder for AWS S3 backend

### ISSUE THREAD

**Issue by kadimulam** [spring-cloud/spring-cloud-config#1577]
How do we specify the configuration to lookup into a folder in S3 bucket? The following configuration worked, but just wanted to find out if there is an explicit configuration for this? Please share the configuration if any.

```
  cloud:
    config:
      server:
        awss3:
          region: us-east-1
          bucket: products-bucket/online-products/sale
          label: test
```
**Note:** `products-bucket` is S3 bucket and `online-products` & `sale `are folders inside the bucket. My files reside in `sale `folder.
