### ISSUE TITLE
can not get multiple config file for one client application

### ISSUE THREAD

**Issue by wxl878725** [spring-cloud/spring-cloud-config#1639]
my config server bootstrap.yml config file is  as follows：
```
spring:
  application:
    name: config-single-server  
  cloud:
    config:
      server:
        git:
          uri: http://git.*******.com/devcenter/{application}.git
          username: ********
          password:*******
          default-label: dev
        #########--------
        health:
          repositories:
            check:
              label: dev
              name: config-repo
              profiles: dev
          enabled: true
    consul:
      host: localhost
      port: 8500
      enabled: true
      token: 80589711-1ef1-27d2-7e96-d2ee0a0213e6
      discovery:
        enabled: true
        register: true
        catalogServicesWatch: true
logging:
  level:
    org.springframework.cloud: debug
    org.springframework.boot: info
```

my config client bootstrap.yml config file is  as follows：
```
spring:
  application:
    name: config-single-client-test
  cloud:
    config:
      uri: http://localhost:3301/
      profile: dev
      name: config-single-client-test,config-single-client,iam-client
      label: dev
      #########------------
      discovery:
        enabled: true
        service-id: config-single-server 
###----------
    consul:
      host: localhost
      port: 8500
      enabled: true
      token: 80589711-1ef1-27d2-7e96-d2ee0a0213e6
      discovery:
        enabled: true
        register: true
        catalogServicesWatch: true
server:
  port: 3302
management:
  security:
    enabled: false
logging:
  level:
    org.springframework.cloud: debug
    org.springframework.boot: info
```

now i want to get multiple config files，include config-single-client-test-dev.properties and iam-client-dev.properties, i can get the property value in config-single-client-test-dev.properties，but i can not get the property value in iam-client-dev.properties，the config server log print ：
DEBUG 15296 --- [nio-3301-exec-2] .s.c.c.s.s.GitCredentialsProviderFactory : Constructing UsernamePasswordCredentialsProvider for URI http://git.******.com/devcenter/config-single-client-test,config-single-client,iam-client.git，but i want all config files of this client applicaiton save in one git http://git.******.com/devcenter/config-single-client-test.git
