### ISSUE TITLE
Usage spring.profiles.include with CompositeRepository

### ISSUE THREAD

**Issue by igor-ermolenko** [spring-cloud/spring-cloud-config#1650]
I have spring cloud config server configured with access to 2 git repositories.

Configuration example:
```
spring:
  profiles:
    active: composite
  cloud:
    config:
      server:
        composite:
          -
            type: git
            uri: https://github.com/myrepo/settings.git
            username: user
            password: pass
          -
            type: git
            uri: https://github.com/myrepo/dictionaries.git
            username: user
            password: pass
```
Also I have different profiles in both repositories. For example:
```
https://github.com/myrepo/settings.git
      application.properties
      application-production.properties

https://github.com/myrepo/dictionaries.git
      application.properties
      application-production.properties
```

When I add `spring.profiles.include=production` into `application.properties` from the first repository I got both files (application.properties, application-production.properties) from first repository and only one (application.properties) from second. And vice versa.

Is it possible to apply `spring.profiles.include' defined in one repository to all other repositories?
