### ISSUE TITLE
Dynamic Repo Credential Provisioning 

### ISSUE THREAD

**Issue by zailushangde** [spring-cloud/spring-cloud-config#1652]
Hi, here is a use case that needs to provision the repo credential via [Github Apps](https://developer.github.com/enterprise/2.20/apps/about-apps/), which results in that the generated token will expire in one hour. Therefore, I am wondering if there is an approach to inject the credential dynamically?

Taking the configuration as an example from below, the `GITHUB_INSTALLATION_TOKEN` is the field will expire.
```
spring:
  cloud:
    config:
      server:
        git:
          uri: https://dummy-link.git
          clone-on-start: true
          ignoreLocalSshSettings: true
          username: ${GITHUB_INSTALLATION_TOKEN}
          password: ${GITHUB_INSTALLATION_TOKEN}
```

Thanks in advance
