### ISSUE TITLE
Access vault secret with specific path

### ISSUE THREAD

**Issue by madiskou** [spring-cloud/spring-cloud-config#1704]
am trying to get my microservices configuration from a config server connected to 2 sources : git and vault (for secrets). I have the config bellow: in the config-server:
```
server:
  port: 8888

spring:
  profiles:
    active: git, vault
  cloud:
    config:
      server:
        vault:
          port: 8200
          host: 127.0.0.1
          kvVersion: 2
        git:
          order: 2
          uri: git@gitlab.git
```
and in the client side in the bootstrap.yml:
```
spring:
  application:
    name: my-service-name

  cloud:
    config:
      uri: http://localhost:8888
      token: //token
      label: dev
```

But in my vault i have the path like this :
```
secret/cad
     |--my-service-name
```

When i make my secret directly in `/secret/my-service-name` i can access my secrets, but how can i configure acces to secrets in : `/secret/cad/my-service-name`

I use:
```
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-dependencies</artifactId>
	<version>Finchley.SR2</version>
	<type>pom</type>
	<scope>import</scope>
</dependency>
```

Thank you.
