### ISSUE TITLE
Using the native profile on Windows

### ISSUE THREAD

**Issue by ctatineni** [spring-cloud/spring-cloud-config#174]
I am trying to retrieve the properties from external file system and some how the properties are not loading, below is what i have in bootstrap.yml file.

```
spring:
  application:
    name: configserver
  cloud:
    config:
      enabled: false
      server:
        native:
          searchLocations: file://c:/properties/    
  profiles:
    active: native
```
