### ISSUE TITLE
How to disable spring.config.import settings in the TestFiles?

### ISSUE THREAD

**Issue by Miles-Ahead-Digital** [spring-cloud/spring-cloud-config#1801]
Hi,
If I use the spring.config.import=optional:configserver in my application.yml (and no bootstrap.yml)
then I'm facing the following issue:

How can I deactivate the spring.config.import in my test classes??
It does not work with properties disabling like "spring.config.enabled=false"
I need to test without configserver.
Please advise

**Comment by ryanjbaxter** [comment]
Did you forget to provide the issue?

**Comment by Miles-Ahead-Digital** [comment]
I want to keep the TestCases and my StandardRuntime in the Spring Default Profile wich contains:
spring.config.import=optional:configserver 

If I run my tests (without having the config server startet), the Test fail because it tries to use the config server. But for the TestCase there is no need to get the yml-config file from the ConfigServer - it works without it..

Best regards
Stefan

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

From my understanding that is not supposed to happen.

**Comment by Miles-Ahead-Digital** [comment]
Hi,

i created https://github.com/Miles-Ahead-Digital/milesahead/tree/master

you can  verify that the spring-profiles do not have any impact on the selection of the values served

Check the Readme.

Best regards
Stefan

**Comment by ryanjbaxter** [comment]
@Miles-Ahead-Digital Not sure I understand how this sample demonstrates the issue.  Your original problem stated that you were having problem with tests failing due to the conig server not running.  I don't see how this sample reproduces that problem.

**Comment by Miles-Ahead-Digital** [comment]
Hi, 
I added a TestCase in the Demo Module. Please read the instruction in the projects readme.
Best regards
Stefan

**Comment by ryanjbaxter** [comment]
The problem you are having is because you are using the wrong properties in your application.yam.  Change it to this and everything works

```
spring.application.name: demo

spring:
  config:
    import: optional:configserver:http://localhost:8888/

message: default-local

---
spring:
  config:
    activate:
      on-profile: test3

message: test3-local

---
spring:
  config:
    activate:
      on-profile: test10

message: test10-local
```
