### ISSUE TITLE
Actuator health check missing details in 3.0.x

### ISSUE THREAD

**Issue by imosapatryk** [spring-cloud/spring-cloud-config#1806]
**Describe the bug**
Hi, using cloud config client version 3.0.0 and native profile for configuration I always get that configuration property sources could not be loaded and status is UNKNOWN when calling the actuator health check.

```
"clientConfigServer": {
  "status": "UNKNOWN",
  "details": {
    "error": "no property sources located"
  }
}
```

Comparing to spring boot 1.x I was receiving:

```
"configServer": {
  "status": "UP",
  "propertySources": [
     "file:C:\\Users\user\projects\tagging.yml",
  ]
}
```

Here is my configuration:

```
spring:
  application:
    name: my-app
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      failFast: false
      retry:
       initialInterval: 10000
       maxInterval: 60000
       maxAttempts: 12
       multiplier: 10.1
```
I see also the log that probably should be "CompositePropertySource" but is Bootstrap one:

`2021-02-23 10:11:15.402  INFO b.c.PropertySourceBootstrapConfiguration : Located property source: [BootstrapPropertySource {name='bootstrapProperties-configClient'}, 
BootstrapPropertySource {name='bootstrapProperties-file:C:\Users\user\properties.yml'}]`
