### ISSUE TITLE
spring.config.import / spring.config.activate.on-profile properties not working as expected with profiles in 2.4.2

### ISSUE THREAD

**Issue by v1nc3n4** [spring-cloud/spring-cloud-config#1807]
Hello,

**Describe the bug**
Environment:
- JDK 11
- Spring Boot: 2.4.2
- Spring Cloud: 2020.0.1

What's happening:
- Test 1: keep config server optional with the `dev` profile, by overriding property `spring.config.import`, and run application *with `dev` profile*.
```yml
# src/main/resources/config/application.yml
spring.config.import: configserver:http://...

# src/main/resources/config/application-dev.yml
spring.config.import: optional:configserver:http://...
```
✖️Application fails immediately because the config server is not reachable, even if it is declared optional in the profile `dev`.

- Test 2: activate config server with the `prod` profile only, using property `spring.config.activate.on-profile`, and run application *with no profile*.
```yml
# src/main/resources/config/application.yml
spring.config.import: configserver:http://...
spring.config.activate.on-profile: prod

application.prop: value
```
✔️Application does not attempt to join the config server
✖️Application fails later because property `application.prop` is null after bean validation with `@NotNull` (seems it has not been loaded correctly from the `application.yml` file).

May be related to other issues created recently in the project, but not sure they are about the exact same problem: #1802, #1801, #1797, #1795
I also tried with Spring Boot 2.4.3 without success.

Thanks in advance for your help.
BR
