### ISSUE TITLE
Inheritance in Config Server in "native" profile with yml not working with Angel.SR3

### ISSUE THREAD

**Issue by marcelalburg** [spring-cloud/spring-cloud-config#181]
Hello,

i use the Inheritance feature in the config server for yml config but since Angel.SR3 is not working anymore.

my setup:

application.yml
```
test:
  url: 123

customserver:
  host: 192.168.0.1

---

spring:
  profiles: dev

customserver:
  host: 127.0.0.1

```

app.yml (no content)
```
```

When i start the config server and call http://localhost:8888/app/dev i just get the server.host and not the "test.url" from application.yml.

if i change the version back to 1.0.0.RELEASE, it works correctly.

Thanks in advance
Marcel

P.s: i create an example project under https://github.com/marcelalburg/SpringConfigServerAngelInheritanceBug

after starting, you can access http://localhost:8888/app/dev and there is no "test.url"
