### ISSUE TITLE
spring.config.import does not recognize list as input in 2020.0.2

### ISSUE THREAD

**Issue by harshadloya** [spring-cloud/spring-cloud-config#1850]
**Describe the bug**
Application fails to startup because the "spring.config.import does not recognize list as input" during the "postProcessEnvironment" validation checks.
Issue started after upgrade from 2020.0.1 to 2020.0.2

**Sample**
Create a simple springboot app using gradle with spring cloud dependency.

build.gradle
```
dependencies {
implementation('org.springframework.boot:spring-boot-starter-web')
implementation('org.springframework.cloud:spring-cloud-starter-config')
}
dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:2020.0.2"
    }
}
```

Application.yml:
```
spring:
  application:
    name: my-test-app
  config:
    import:
      - optional:configserver:\<dev url>
      - optional:configserver:\<test url>
      - optional:configserver:\<prod url>
```
