### ISSUE TITLE
Profile groups are not honored by client

### ISSUE THREAD

**Issue by nickcaballero** [spring-cloud/spring-cloud-config#1876]
I reported this in spring-boot but the issue is with the spring-cloud-config client.

https://github.com/spring-projects/spring-boot/issues/26116

----

Using a config server, in the application.yml I have defined a group:

```
# application.yml

spring:
  profiles:
    group:
      dev:
        - local
        - other
```

In my application configuration, I'm making use of the `other` profile:

```
# my-service.yml

spring:
  datasource:
    url: jdbc:...

---

spring:
  config:
    activate:
      on-profile: other

some:
  other:
    setting: true
```

When running the application with the `dev` profile, I expected to see the `some.other.setting=true` property. However, the file seems to be skipped and the property is therefore missing. Looking at the output of the HTTP request to config server, I see that both documents in `my-service.yml` are returned - the default and the one activated by the `other` profile.

I'm currently using Spring Boot 2.4.4 and Spring Cloud Config Client 3.0.3.
