### ISSUE TITLE
Application property files always pulled by default

### ISSUE THREAD

**Issue by mn-ar** [spring-cloud/spring-cloud-config#1935]
Hi

I have setup a spring cloud config server (2.2.3.RELEASE) with the following configuration:

```
spring:
  application:
    name: config-server
  profiles:
    active: composite
  cloud:
    config:
      server:
        composite:
          - type: git
            uri: <uri1>
            username: <uname>
            password: <pass>
            cloneOnStart: true
            force-pull: true
            basedir: <basedir1>
            timeout: 2
            refreshRate: 120
          - type: git
            uri: <uri2>
            username: <uname>
            password: <pass>
            cloneOnStart: true
            force-pull: true
            basedir: <basedir2>
            timeout: 2
            refreshRate: 120
```

The first git repo contains configuration file with the name _myproject-dev.yml_ and the second one contains configuration file with name _application-dev.yml_

When the config client with _spring.config.name = myproject_ pulls data from config server (using _dev_ profile), the _application-dev.yml_ file from the second repo comes along.

Is this an expected behavior? Is there any way to prevent getting _application-dev.yml_ files along? Or, a way to specify application name with the git configuration parameters such that _myproject_ is able to access only the first git repo.
