### ISSUE TITLE
False positive of ConfigServerConfigDataMissingEnvironmentPostProcessor

### ISSUE THREAD

**Issue by hpoettker** [spring-cloud/spring-cloud-config#1943]
With Spring Boot 2.5.3, Spring Cloud 2020.0.3, and Spring Cloud Config 3.0.4, I get a false positive from the `ConfigServerConfigDataMissingEnvironmentPostProcessor` that is similar to #1849. The difference is that `spring.config.import` is not only a list but also nested. 😄 

The full minimal example can be found here: https://github.com/hpoettker/scc-sample

The essential files are in the client's resource directory. The `application.yml`:

```
spring:
  application:
    name: client

  config:
    import:
      - configserver:http://localhost:8888
      - classpath:/additional-config.yml

  cloud:
    config:
      username: user
      password: password
```

The `additional-config.yml`:
```
spring:
  config:
    import: classpath:/sub-config.yml
```

The `sub-config.yml`:
```
client:
  config:
    yada: yadayada
```

When I add the property `spring.cloud.config.import-check.enabled=false`, then everything works smoothly.
