### ISSUE TITLE
client has multi config-servers support?

### ISSUE THREAD

**Issue by aliciz** [spring-cloud/spring-cloud-config#1975]
Scenario: the company provides a globally unified config-server, but my project provide an internal config-server. Therefore, client needs to configure two or multi config-servers url.

I want a features of properties look like:
```
spring:
  config:
    import:
      - optional:configserver:http://global-config-server:8888
      - optional:configserver:http://project-config-server:8888
```
