### ISSUE TITLE
why my ConfigurationProperties bean not refreshed with a property types of map?

### ISSUE THREAD

**Issue by jackding79** [spring-cloud/spring-cloud-config#1978]
my configuration bean has a property like Map<String,String>,when I remove  key , refresh not worked。
this is my yaml in config center.
```yaml
test:
  maps:
    k1: v1
    k2: v2 
```
I delete   k2:v2 ，there has still k2:v2.
