### ISSUE TITLE
When using spring.config.import with configserver , we cannot override with local files

### ISSUE THREAD

**Issue by tsemachh** [spring-cloud/spring-cloud-config#2006]
Hi
When using new Spring Boot spring.config.import with configserver , we cannot override with local files

**application.yml**
```
spring:
  application:
    name: api-gateway
  profiles:
    active: devgateway  #,integ4,prod
  config:
    import: "optional:configserver:http://hrhadad.snifim.blroot:8889,developer.yml"
```
**Config Server GIT** (Tried also other combinations)
```
spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
apache.server=http://localhost:9080
```
**developer.yml**
`apache.server: http://localhost:18090`

Expected apache.server to be http://localhost:18090
Actually we got http://localhost:9080

The only way we managed to override was using application.properties , we do expect that order will matter in this case/
thx
tsemach
