### ISSUE TITLE
ConfigServerInstanceProvider$Function has not been registered in kubernetes

### ISSUE THREAD

**Issue by mschneid0207** [spring-cloud/spring-cloud-config#2009]
Hello together,

I migrated from Spring Boot 2.3.2 to 2.5.6. 
When starting up the services and using eureka as service discovery everything is running fine. All my client services are finding correctly the spring cloud config service and fetching their configurations from it. 
But when I use the service discovery from spring cloud kubernetes (spring-cloud-starter-kubernetes-all) I always getting the following error.

I always get the following error.
java.lang.IllegalStateException: org.springframework.cloud.config.client.ConfigServerInstanceProvider$Function has not been registered
	at org.springframework.boot.DefaultBootstrapContext.lambda$get$1(DefaultBootstrapContext.java:88)
	at org.springframework.boot.DefaultBootstrapContext.getOrElseThrow(DefaultBootstrapContext.java:109)
	at org.springframework.boot.DefaultBootstrapContext.get(DefaultBootstrapContext.java:88)
	at org.springframework.cloud.config.client.ConfigServerConfigDataLocationResolver.lambda$resolveProfileSpecific$8(ConfigServerConfigDataLocationResolver.java:196)
........

Here is my config in the application.yml of one of my client services (e.g. customer-service).

```
spring:
  application:
    name: customer-service
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service
      retry:
        max-attempts: 10
      fail-fast: true
```
I tested it with spring cloud dependencies 2020.0.0 - 2020.0.4. But I am always getting the following error.
Also I tested with different version of spring-cloud-starter-kubernetes-all.
I always getting the same error.

Thanks a lot for your support.

Regards
Markus
