### ISSUE TITLE
Git always wins in a composite version

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-config#2040]
Having the following composite setup for config server (2021.0.0, Boot 2.6.3)

```bash
$ curl https://start.spring.io/starter.tgz -d dependencies=cloud-config-server,cloud-starter-vault-config \
-d language=java -d type=maven-project -d baseDir=spring-cloud-config-server | tar -xzvf -
```

Annotated the class with `@EnableConfigServer`

.application.yml
```yml
spring:
  cloud:
    vault:
      # [Vault] token
      token: vault-plaintext-root-token
    config:
      server:
        composite:
          - type: vault
            kv-version: 2
          - type: git
            uri: https://github.com/marcingrzejszczak/config-server-properties
  profiles:
    # [Vault & git]
    active: composite

# default port
server.port: 8888
```

Inserting such vault entries

```bash
$ vault kv put secret/bar,foo a="bar with foo profile value from Vault"
```

Having such git repo 

.bar-foo.properties 
```properties
a=default with foo profile value from git
```

When sending a request to retrieve the properties for app `bar` with profile `foo` I get back `a` from git not from `vault`

```
curl localhost:8888/bar-foo.properties -H "X-Config-Token: vault-plaintext-root-token"
```

When I remove git from the composite setup I get `a` equal to `bar with foo profile value from Vault`

**Comment by dantonyuk** [comment]
@marcingrzejszczak Please try this:

```yaml
spring:
  cloud:
    config:
      server:
        vault:
          order: 1
          ...
        git:
          order: 2
          ...
```

and use profile `git,vault`.
