### ISSUE TITLE
Proxy handle  should skip empty description

### ISSUE THREAD

**Issue by antechrestos** [spring-cloud/spring-cloud-config#2088]
Currently I would like to provide an environment based configuration like so

```
spring:
  config:
    activate:
      on-profile: config-server
  cloud:
    config:
      server:
        bootstrap: ${CONFIG_SERVER_BOOTSTRAP}
        git:
          uri: ${CONFIG_SERVER_GIT_URI}
          clone-on-start: ${CONFIG_SERVER_GIT_CLONE_ON_START}
          default-label: ${CONFIG_SERVER_GIT_DEFAULT_LABEL}
          basedir: ${CONFIG_SERVER_GIT_BASEDIR} # This variable must not end with a '/' for a directory
          # http properties: see https://cloud.spring.io/spring-cloud-config/multi/multi__spring_cloud_config_server.html#_authentication
          username: ${CONFIG_SERVER_GIT_HTTP_USERNAME:#{null}}
          password: ${CONFIG_SERVER_GIT_HTTP_PASSWORD:#{null}}
          proxy:
            http:
              host: ${CONFIG_SERVER_HTTP_PROXY_HOST}
              port: ${CONFIG_SERVER_HTTP_PROXY_PORT}
```

With so, I may provide an `application.yml` file based on environment.
Everything works fine but the proxy part: in face, as long as it is declared, it is used. I think that a mere check (host ot empty and port positive) should be done in order to allow a generic declaration.
