### ISSUE TITLE
Not supporting multiple profile in same application yml

### ISSUE THREAD

**Issue by jacky7788** [spring-cloud/spring-cloud-config#2109]
Using spring cloud config 3.1.3
Embedded server and using s3 as backend

bootstrap.yml

```
spring.profiles.active:
  - uat
  - awss3
spring.cloud.config.server:
  bootstrap: true
  awss3:
    region: ap-east-1
    bucket: bucketname
```

application.yml
```
spring.config.activate.on-profile: uat
......
---
spring.config.activate.on-profile: prod
.......
```

It seems cannot handle multi profile in same yml
org.springframework.cloud.config.server.environment.AwsS3EnvironmentRepository

```
class YamlS3ConfigFile extends S3ConfigFile {

	final InputStream inputStream;

	YamlS3ConfigFile(String version, InputStream inputStream) {
		super(version);
		this.inputStream = inputStream;
	}

	@Override
	public Properties read() {
		final YamlPropertiesFactoryBean yaml = new YamlPropertiesFactoryBean();
		try (InputStream in = inputStream) {
			yaml.setResources(new InputStreamResource(in));
			return yaml.getObject();
		}
		catch (IOException e) {
			throw new IllegalStateException("Cannot load environment", e);
		}
	}

}
```
the yaml properties here using ConcurrentHashMap to store
not sure if this is the design
