### ISSUE TITLE
Embedded configuration server does not load application properties

### ISSUE THREAD

**Issue by taxone** [spring-cloud/spring-cloud-config#2129]
I'm using Spring Cloud Config 3.1.3 with Spring Boot 2.7.2.
I created an embedded configuration server using the instructions contained in [the official documentation](https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#_embedding_the_config_server).

My goal is embedding the configuration server into an application. The application should load the configuration properties provided by the embedded configuration server using a custom *EnvironmentRepository*.
It seems that this should be possible:

```
If you want to read the configuration for an application directly from the backend repository (instead of from the config server), you basically want an embedded config server with no endpoints
```

But the configuration properties are not loaded.
This is the sample project:

https://github.com/taxone/embedded-config-server

The custom repository works fine if the endpoint below is called:

http://localhost:8888/config/application/default

and the response is:

```
{
  "name": "application",
  "profiles": [
    "default"
  ],
  "label": null,
  "version": null,
  "state": null,
  "propertySources": [
    {
      "name": "test",
      "source": {
        "pippo.name": "ciao"
      }
    }
  ]
}
```

but the property is **not** injected:

```
@Configuration
@ConfigurationProperties(prefix = "pippo")
public class Embedde2Properties {

	@Getter
	@Setter
	private String name;
}
```

It seems that someone else had a similar issue on [stack overflow](https://stackoverflow.com/questions/69188127/spring-cloud-embedded-config-server-with-native-repository).

**Comment by ryanjbaxter** [comment]
Can you try adding the dependency `spring-cloud-starter-bootstrap`?

Also can you move 
```
spring:
  application:
    name: myconfigserver
  profiles:
    active: composite
  cloud:
    config:
      server:
        prefix: /config
        bootstrap: true
        composite:
          - type: prova 
```
too bootstrap.yml
