### ISSUE TITLE
Ref master cannot be resolved

### ISSUE THREAD

**Issue by baasanbat** [spring-cloud/spring-cloud-config#2157]
**Description**
It's been a while since github changes 'master' branch name to 'main'. It seems like whatever I try config server tries to pull from branch name 'master' so that we get the error message 'Ref master cannot be resolved'. I put spring.cloud.config.server.git.default-label: main, I got no success.

**Sample**
```
spring:
  cloud:
    config:
      server:
        git:
          uri: private-repo-url
          default-label: main
          username: uname
          password: pwd
          clone-on-start: true
```
I have registry.yml on my repo. When I try to URL/registry/default/main, or either URL/registry/default I get the above exceptions.
