### ISSUE TITLE
Cloud Config Native Environment Health Check Always Good

### ISSUE THREAD

**Issue by DeezCashews** [spring-cloud/spring-cloud-config#219]
If you use `spring.cloud.config.server.native.search-locations` for testing then `spring.cloud.config.server.health.repositories` doesn't do anything because it seems to always create an environment even if an associated file doesn't exist.

**Comment by spencergibb** [comment]
A normal `SpringApplication` is used to create the environment.  That is it's normal behavior: it creates an environment even if it can't find anything to add to it.

**Comment by DeezCashews** [comment]
Then maybe the health check could be changed to check if that is the case so that it doesn't give a false positive.

**Comment by spencergibb** [comment]
How would you change it?

**Comment by DeezCashews** [comment]
Maybe I'm not understanding how `ConfigServerHealthIndicator` is supposed to work.  It only shows 'DOWN' if there is an exception finding an environment given an application name, profile, and label "combo".  I thought this would be useful to know if a config server doesn't have a required configuration "combo", but if an environment exists for any combo then I don't see how it will ever be anything but 'UP'.  Is the health check just there for connectivity (which makes sense with Git or SVN but of course not Native) and I'm trying to use it wrong?

**Comment by spencergibb** [comment]
which `ConfigServerHealthIndicator` are you talking about?  The one in the `client` package or `server`?

**Comment by DeezCashews** [comment]
The `server`.  http://projects.spring.io/spring-cloud/spring-cloud.html#_health_indicator  I'm trying to take advantage of the additional checks like so:

```
spring:
  cloud:
    config:
      server:
        health:
          repositories:
            myservice:
              label: mylabel
            myservice-dev:
              name: myservice
              profiles: development
```
