### ISSUE TITLE
Skip default property on Multi-document property files and Activation profile

### ISSUE THREAD

**Issue by Murik** [spring-cloud/spring-cloud-config#2195]
**Describe the bug**
I have Config Server with File System Backend for several microservices. It contains hierarchy yaml resources with default(for all) and ms specific properties.

Spring Boot 2.7.6
Cloud 2021.0.5 ( Config Server 3.1.5)
```
config/
---application.yml
---microservice-one.yml
```

Both resources contains default and profile specific property.
application.yml
```
value: value-for-profile-override
all-value: value-for-all-ms
---
spring:
  config:
    activate:
      on-profile: dev
value: value-dev
dev-all-ms-value: value-dev-for-all-ms
---
spring:
  config:
    activate:
      on-profile: prod
value: value-prod
dev-all-ms-value: value-prod-for-all-ms
```

microservice-one.yml
```
one-value: ms-one-all-profile-value
---
spring:
  config:
    activate:
      on-profile: dev
dev-one-value: ms-one-dev-profile-value
---
spring:
  config:
    activate:
      on-profile: prod
dev-one-value: ms-one-prod-profile-value
```
I try to read config with profile 'dev' for my ms. Both property sources is returned, but application.yml contains only profile depend part.

curl http://localhost:8888/microservice-one/dev

```
{
  "name": "microservice-one",
  "profiles": [
    "dev"
  ],
  "label": null,
  "version": null,
  "state": null,
  "propertySources": [
    {
      "name": "Config resource 'class path resource [config/microservice-one.yml]' via location 'optional:classpath:/config/' (document #1)",
      "source": {
        "spring.config.activate.on-profile": "dev",
        "dev-one-value": "ms-one-dev-profile-value"
      }
    },
    {
      "name": "Config resource 'class path resource [config/microservice-one.yml]' via location 'optional:classpath:/config/' (document #0)",
      "source": {
        "one-value": "ms-one-all-profile-value"
      }
    },
    {
      "name": "Config resource 'class path resource [config/application.yml]' via location 'optional:classpath:/config/' (document #1)",
      "source": {
        "spring.config.activate.on-profile": "dev",
        "value": "value-dev",
        "dev-all-ms-value": "value-dev-for-all-ms"
      }
    }
  ]
}
```

Response missed part with "all-value: value-for-all-ms" property. But contains same 'profile independet' part from microservice-one.yml

I have an [bug demo project](https://github.com/Murik/demo-config-server) to reproduce the problem/

This behavior worked fine on 2.2.6 version of CFS.
