### ISSUE TITLE
Passphrase is not used during ssh connection establishment

### ISSUE THREAD

**Issue by bvn13** [spring-cloud/spring-cloud-config#2201]
**Describe the bug**
SpringBoot version 3.0.0 
SpringCloud version 2022.0.0

According to docs https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#_authentication
I generated keypair adding keyphrase.
Then I specified this passphrase into application properties on branch `spring.cloud.config.server.git.passphrase`.
And this phrase was ignored during connection establishment to git server located at url like template `ssh://git@server:port/path/to/repo`

**Sample**
1. generate keypair with passphrase not empty using
`ssh-keygen -m PEM -t rsa -b 4096 -f ~/config_server_deploy_key.rsa`
2. add to ~/.ssh/config these lines
```
Host gitea.my.server
    HostName gitea.my.server
    IdentityFile ~/.ssh/config_server_deploy_key.rsa
    Port 2221
```
3. create initial config-server application with such properties
```
spring:
  cloud:
    config:
      server:
        git:
          uri: ssh://git@gitea.my.server:2221/path/to/repo.git
          clone-on-start: true
          ignore-local-ssh-settings: false
```
4. try to run simple test
```
@SpringBootTest
class ConfigServerApplicationTests {

    @Test
    void contextLoads() {
    }

}
```
5. these steps leads to login exception

---
My investigation of this issue.

Exception is thrown from `PassphraseCredentialsProvider.java`: 
```
  @Override
  public boolean get(URIish uri, CredentialItem... items) throws UnsupportedCredentialItem {
    for (final CredentialItem item : items) {
      if (item instanceof CredentialItem.StringType && item.getPromptText().startsWith(PROMPT)) {
        ((CredentialItem.StringType) item).setValue(this.passphrase);
        continue;
      }
      throw new UnsupportedCredentialItem(uri, item.getClass().getName() + ":" + item.getPromptText()); // HERE
    }
    return true;
  }
```

params in my case are:
1. constant PROMPT = Passphrase for
2. phrase from ssh: Key '/home/bvn13/.ssh/config_server_deploy_key.rsa' is encrypted. Enter the passphrase to decrypt it.
3. item instanceof CredentialItem.StringType is FALSE
4. item.getPromptText().startsWith(PROMPT) is FALSE

It leads me to idea that there is no CredentialProvider applicable to this kind of authorization (key + phrase).

So my questions are:
1. is this a bug?
2. what is `spring.cloud.config.server.git.passphrase` intended for?
3. how to apply custom CredentialProvider for such cases?

UPDATE:
Connection is established OK after I regenerate keypair lefting passphrase empty and refresh my key into Gitea server.

**Comment by ryanjbaxter** [comment]
So its working now?

**Comment by bvn13** [comment]
No, the issue is:
Config Server is unable to connect if private key is generated with keyphease.

**Comment by ryanjbaxter** [comment]
>UPDATE:
>Connection is established OK after I regenerate keypair lefting passphrase empty and refresh my key into Gitea server.

Does this mean if your key doesn't have a passphrase it works?


This is not valid
```
spring:
  cloud:
    config:
      server:
        git:
          uri: ssh://git@gitea.my.server:2221/path/to/repo.git
```

It should be 
```
spring:
  cloud:
    config:
      server:
        git:
          uri: git@gitea.my.server:2221/path/to/repo.git
```
