### ISSUE TITLE
Use multiple repositories for one application

### ISSUE THREAD

**Issue by dominikjeske** [spring-cloud/spring-cloud-config#2213]
I'm trying to figure out how to do such use case with config server: Each app has its own repository (I named apps sharka, sharkb...) this is easy with pattern for repositories but.. applications are also using external components that have its own configuration I named it ComponentA, ComponentB... So the question is - how to load more then one configuration (for example sharka+ComponentB). 

```
spring:
  profiles:
   active: git
  cloud:
    config:
      server:
        git:
          uri: https://xxx/scm/arch/poc_configserver_teama.git
          repos:
            ComponentA:
              pattern: 'ComponentA'
              uri: https://xxx/scm/arch/poc_configserver_componentA.git
            ComponentB:
              pattern: 'ComponentB'
              uri: https://xxx/scm/arch/poc_configserver_componentB.git
            sharka:
              pattern: sharka
              uri: https://xxx.com/scm/arch/poc_configserver_teama.git
            sharkb:
              pattern: sharkb
              uri: https://xxx.com/scm/arch/poc_configserver_teamb.git
```

I tried pattern matching to match more then one result (I tried component as other profile '*/ComponentA') but it stops after first finding so this was dead end.

I also tried composite but I think it is not working with [multi repo](https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#_pattern_matching_and_multiple_repositories ). There is no docs for this and this pseudo code is not working

```
spring:
  profiles:
   active: composite, git
  cloud:
    config:
      server:
        git:
          uri: https://xxx/scm/arch/poc_configserver_teama.git
          repos:
            sharka:
              pattern: sharka
              composite:
              -
                type: git
                uri: https://xxx/scm/arch/poc_configserver_teama.git
              -
                type: git
                uri: https://xxx/scm/arch/poc_configserver_hostapicache.git
            sharkb:
              pattern: sharkb
              uri: https://xxx/scm/arch/poc_configserver_teamb.git

```

Is there any working solution for this?

**Comment by ryanjbaxter** [comment]
A composite configuration is the way to go, but your composite configuration isn't right, here is an example from our docs.

```
spring:
  profiles:
    active: composite
  cloud:
    config:
      server:
        composite:
        -
          type: svn
          uri: file:///path/to/svn/repo
        -
          type: git
          uri: file:///path/to/rex/git/repo
        -
          type: git
          uri: file:///path/to/walter/git/repo
```
