### ISSUE TITLE
S3 and Git backends have different behaviors for file handling

### ISSUE THREAD

**Issue by tjg184** [spring-cloud/spring-cloud-config#2216]
**Describe the bug**
Spring Cloud Version: `2022.0.0`

We are comparing a Git and S3 backend to better understand the differences, specifically for serving text files. There's some different behavior between requesting files between the S3 and Git backends and was trying to understand why this is expected. 

Unless we're misunderstanding, it makes switching out the back-ends impact the clients. Only handling JSON files in S3 is fine for now, but we would have expected the application name and routes to be consistent between the two back-ends.

In the S3 implementation, it's treating the `{application}` as part of the object key prefix so the following requests work differently between the back-ends.   

Git:
`curl localhost:8080/foo/default/master/data1.json` (works)

S3:

`curl localhost:8080/foo/default/master/data1.json` (does not work)
`curl localhost:8080/foo/default/master/data1` (does not work)
`curl localhost:8080/data/default/master` (works)

Thanks for any guidance. 

**Sample**

Git Repo and Bucket have a single file called `data1.json`. In Git, it is in the `master` branch. In the S3 bucket, there is a `master` folder in bucket `bucket1`

S3 Config
```
awss3:
  bucket: bucket1
  region: us-east-1
  endpoint: http://localhost:9000
```

Git Config
```
git:
  uri: file:///Users/tgaines/dev/config-data
  default-label: master
  clone-on-start: true
```
