### ISSUE TITLE
Search paths is not woking if use-legacy-processing sets to true in config repo

### ISSUE THREAD

**Issue by zacscoding** [spring-cloud/spring-cloud-config#2333]
**Describe the bug**
If our config repo has `spring.config.use-legacy-processing=true` in application.yml and use search paths in config server,
Then returns empty environments becase of `;` delimiter at [NativeEnvironmentRepository](https://github.com/spring-cloud/spring-cloud-config/blob/main/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/NativeEnvironmentRepository.java#L233) which updated from #1904.

If this is within the provided specification, please close the issue :) thx!

**Sample**
- **Config Repo**
```
tree ./
./
├── app
│   └── application.yml
└── data
    └── db.yml
```

app/application.yml

```
...
spring:
  config:
    use-legacy-processing: true
...
```

- **Config Server**

application.yml
```
spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/myrepo
          search-paths:
            - app
            - data
```
