### ISSUE TITLE
[Question] spring cloud config server not recognize file

### ISSUE THREAD

**Issue by leechoongyon** [spring-cloud/spring-cloud-config#2344]
I use spring cloud config server in spring boot.

There are two files in spring cloud config server repository.

common.yml
hazelcast-common.yml

```yaml
#common.yml
spring:
  hazelcast:
    config: classpath:hazelcast-common.yml
```

```yaml
#hazelcast-common.yml
hazelcast:
   ...
   ...
   ...
```

```yaml
#client yml 

spring:
  config:
    import:
      configserver:http://localhost:8888

```

**spring cloud config client run -> recognize common.yml -> but not recognize hazelcast-common.yml** 

**client error log**
```Caused by: java.lang.IllegalArgumentException: Hazelcast configuration does not exist 'class path resource hazelcast-common.yml```
