### ISSUE TITLE
spring cloud config server in docker

### ISSUE THREAD

**Issue by VinncentWong** [spring-cloud/spring-cloud-config#2373]
**Describe the bug**
I have config server application and one service too that is wrapped in a docker container. However, when trying to connect to config server application, I can't connect. I already change the host name into the docker container, change it into the IP address/Gateway from the config server container, however it's still can't connect. 

(But, if I access it through host by calling `localhost:8000/orangtua-service/default`, it shows the result)
![image](https://github.com/spring-cloud/spring-cloud-config/assets/88434717/28e77ac7-4705-4775-9465-ecf507845ce0)

**Sample**
```
docker-compose
version: '3.7'
services:
  ...
  config-server:
    container_name: config-server
    build: ./config-server
    restart: on-failure
    ports:
      - "8000:8000"
    expose:
      - 8000
    networks:
      - sipas_network
  parent-service:
    container_name: parent-service
    build: ./parent-service
    restart: on-failure
    depends_on:
      - config-server
    environment:
      - config-server.host=config-server
    ports:
      - "8002:8002"
    expose:
      - 8002
    networks:
      - sipas_network
volumes:
  mysql_volume:
    name: mysql_volume
networks:
  sipas_network:
```
```
bootstrap.yaml on parent-service
# =============================== SPRING CFG ===========================================
spring:
  application:
    name: orangtua-service
  config:
    import: configserver:http://${config-server.host}:8000/
  main:
    web-application-type: reactive

# =============================== SERVER CFG ===========================================
server:
  port: 8002
```

![image](https://github.com/spring-cloud/spring-cloud-config/assets/88434717/fbb8c180-9377-40eb-b412-6a5c68bd9ece)

Do I miss something? Since it works on localhost but not work on docker?
 Thank you
