### ISSUE TITLE
Question: resolving maps by properties/yml endpoint

### ISSUE THREAD

**Issue by Ferioney** [spring-cloud/spring-cloud-config#2400]
Hi,
I would like to clarify "maps" behaviour when fetching `properties`/`yaml` configuration from `spring-cloud-configuration-service`.

Lets say I have two configuration files:
**application-dev.yml**
```
service:
  configuration:
    1:
      topic: "topic 1"
```

**application-prod.yml**
```
service:
  configuration:
    2:
      topic: "topic 2"
```
I use endpoint `/{label}/{service-name}-{profiles}.properties` (from `EnvironmentController`), profiles=dev,prod. Maps are overridden (logic of overrides [EnvironmentController#convertToProperties](https://github.com/spring-cloud/spring-cloud-config/blob/main/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/EnvironmentController.java#L315)). 
But when I use `spring-cloud-config-client` to load configuration maps are merged.  
So my question, is it expected behaviour for properties/yml endpoint? If yes why it's different from client property resolving?
