### ISSUE TITLE
PropertySources not loading, [] is returned

### ISSUE THREAD

**Issue by sqilz** [spring-cloud/spring-cloud-config#2430]
**Describe the bug**
Fetch configs using rest API stopped does not returning propertySources and returns an empty array, it literally did work this morning, and I have not modified the server since yesterday

- jdk17
- spring boot 3.2.6
- cloud 2023.0.1

**Sample**

`curl localhost:8888/my-command/dev` or `curl localhost:8888/my-command/dev/main` returns the latest commit info but no property sources
```
{
    "label": null,
    "name": "my-command",
    "profiles": [
        "dev"
    ],
    "propertySources": [],
    "state": null,
    "version": "803cf2c86599e2f12f4bd9b69231207c5b078188"
}

```

```
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info

spring:
  application:
    name: config.server
  cloud:
    config:
      server:
        git:
          uri: git@ssh.gitlab/Example/app-configs.git
          strictHostKeyChecking: false
          ignoreLocalSshSettings: true
          search-paths: {application}
          default-label: main
          clone-on-start: true
          force-pull: true
          try-master-branch: false
          basedir: repo
          private-key: |
```

Repostitory files
```
├── my-command
│   ├── application-DEV.yaml
│   └── application-SBX.yaml
```
