### ISSUE TITLE
Property Order is not working in Composite Environment Repositories

### ISSUE THREAD

**Issue by srikanth716** [spring-cloud/spring-cloud-config#2438]
order property to specify the priority order for all repositories. The lower the numerical value of the order property, the higher priority it has. The priority order of a repository helps resolve any potential conflicts between repositories that contain values for the same properties. But when I tried to implement the order the priority is not changing.

[Document](https://cloud.spring.io/spring-cloud-config/multi/multi__spring_cloud_config_server.html#composite-environment-repositories)

[GitHub Link](https://github.com/srikanth716/configServer.git)

Current response: Data Response: eng,ara,fra

Expected response: Data Response: eng,ara,fra,khm

```
//application.yml 

server:
  port: 8888

spring:
  application:
    name: config-server

  profiles:
    active: composite

  cloud:
    config:
      server:
        composite:
          - type: git
            uri: https://github.com/mosip/mosip-config 
            clone-on-start: true
            # Add the branch if not using main
            default-label: develop
            searchPaths: /
            order: 2
          - type: git
            uri: https://github.com/srikanth716/inji-config
            clone-on-start: true
            default-label: develop
            searchPaths: /
            order: 1
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud: DEBUG
```
