### ISSUE TITLE
not able to use cipher in bootstrap.yml

### ISSUE THREAD

**Issue by imod** [spring-cloud/spring-cloud-config#248]
It seems that it is not possible to use `{cipher}` in the bootstrap.yml.
I created a simple example project showing the issue: https://github.com/imod/spring_boot_demo

The bootstrap.yml looks like this
```
encrypt:
  key: ${ENCRYPT_KEY:dummy}

my:
  password: '{cipher}c6e87846e7155dc7d86d5b850d8c8551c5fe41b625acdee4c85e7ef3a68a719f'
```
it also does not matter if I set `ENCRYPT_KEY=dummy` as an environment variable.

...at startup the `DemoApplication.afterPropertiesSet()` is expected to print the decrypted value.
