### ISSUE TITLE
Unable to Load Configuration from S3 Folder using Spring Cloud Config: Key Not Found

### ISSUE THREAD

**Issue by BeardDude** [spring-cloud/spring-cloud-config#2531]
### Issue Description:
I'm trying to access configuration files located inside a folder in an S3 bucket using Spring Cloud Config. Below is the folder structure in S3:

```
bucket1/
└── config/
    └── application-dev.yml
```

Here is the relevant Spring configuration:

```yaml
spring:
  profiles:
    active: awss3
  cloud:
    config:
      server:
        awss3:
          region: us-east-1
          bucket: bucket1/config
```

When trying to access the configuration via `http://localhost:8888/application/dev`, I am encountering an issue. The debug logs indicate that the S3 key was not found. The encoded URL appears as `/bucket1%2Fconfig/application-dev.yml`, and it seems like the folder structure or path encoding might be the cause.

### Debug Log Excerpt:
```
Key not found: /bucket1%2Fconfig/application-dev.yml
```

### Question:
How can I resolve this issue to correctly access the `application-dev.yml` file from the `config` folder in the S3 bucket?

(or)

Support for subfolders in a S3 bucket is not available ?

### Package versions:

spring-cloud-config-server - 4.1.3
software.amazon.awssdk (s3) - 2.28.1

Any help or suggestions would be appreciated!
