### ISSUE TITLE
Separate Spring Config Repositories for every application

### ISSUE THREAD

**Issue by denschu** [spring-cloud/spring-cloud-config#257]
I'm actually thinking about how to configure Spring Cloud Config in an enterprise environment. I don't want to put all the configs in one repository or in one repo separated by stage/team or whatever. It would be great if it's possible to have one repository per application. In that case we need pattern matching in the uri-part of the server-config like that:

```
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/app-configuration/${client.spring.application.name}
```
or maybe in combination with profile-based-separation:

```
spring:
  cloud:
    config:
      server:
        git:
          repos:
            development:
              pattern:
                - */development
              uri: https://github.com/dev-configuration/${client.spring.application.name}
            staging:
              pattern:
                - */production
              uri: https://github.com/prod-configuration/${client.spring.application.name}
```

Another advantage is, that we never have to modify the configuration of the config server, when there is a new application/team/etc., because it's only a convetion on how to name the repositories. Does this make sense for you? :-)
