### ISSUE TITLE
Proxy configuration not working in Spring Cloud Config

### ISSUE THREAD

**Issue by moiMeme** [spring-cloud/spring-cloud-config#2608]
**Describe the bug**
When configuring a proxy in Spring Cloud Config, HTTP requests to the config server do not route through the specified proxy. Despite setting http.proxyHost and http.proxyPort (or equivalent settings in application.yml), the connection bypasses the proxy and connects directly. This issue impacts users who require proxy routing for secure or restricted network environments.

**Step to reproduce**

1. Set up a Spring Boot project with the following dependencies:
```
 <dependencies>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter</artifactId>
    </dependency>
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-config</artifactId>
    </dependency>
</dependencies>
```

2. Configure the proxy settings in application.yml:
```
spring:
  cloud:
    config:
      server:
        defaultLabel: master
        git:
          deleteUntrackedBranches: true
          clone-on-start: true
          skipSslValidation: true
          searchPaths:
            - "{application}"
            - "{application}/{profile}"
          uri: "https://config-server-url"  # Replace with your config server URL
          proxy:
            host: "proxy.example.com"       # Replace with your proxy hostname
            port: 8080                      # Replace with your proxy port
```

3. Start the Spring Boot application. Verify if requests to the config server route through the specified proxy (e.g., by checking proxy logs)

**Expected Behavior**
Requests to the config server should be routed through the configured proxy (proxy.example.com:8080).

**Actual Behavior**
Requests to the config server bypass the configured proxy and connect directly. Proxy logs show no incoming requests, confirming that the proxy is not being used.

**Environment**

- Spring Cloud Version: 2023.0.3
- Spring Boot Version: 3.3.5
- Java Version: 21
- Environment: Docker, Kubernetes, or local

**Additional Context**
No related exceptions or errors appear in the logs. The following configurations were tested without success:
- *Environment Variables:* http.proxyHost and http.proxyPort.
- *Java System Properties:* -Dhttp.proxyHost=proxy.example.com -Dhttp.proxyPort=8080.
- Direct Configuration in application.yml.

**Workaround Solution**
To route requests through the proxy despite the original configuration issue, I extended HttpClientConfigurableHttpConnectionFactory and modified the create method to ensure a new proxy is always created if none is provided or if the proxy type is set to DIRECT. This approach successfully routed requests through the proxy as expected. (not a good solution)

Here’s a summary of the code:

```
public class CustomHttpConnectionFactory extends HttpClientConfigurableHttpConnectionFactory {

    @Override
    public HttpConnection create(URL url, Proxy proxy) throws IOException {
        // Check if the proxy is null or has a direct type
        Proxy newProxy = Optional.ofNullable(proxy)
                      .filter(pp -> !Proxy.Type.DIRECT.equals(pp.type()))
                      .orElse(new Proxy(Proxy.Type.HTTP, new InetSocketAddress("proxy.example.com", 3128)));
        return super.create(url, newProxy );
    }
}
```
In this method:

If the provided proxy is null or of type DIRECT, it creates a new Proxy instance with Proxy.Type.HTTP and the desired proxy host and port.
This successfully routes the request via the specified proxy.(for test purpose)
