### ISSUE TITLE
New zuul routes not added in order after call to "/refresh"

### ISSUE THREAD

**Issue by hacbq** [spring-cloud/spring-cloud-config#274]
As I see in spring-cloud/spring-cloud-netflix#196. This bug fixed.
I have zuul config
```
zuul:
  ignoredServices: '*'
  routes:
    admin:
      path: /admin/**
      stripPrefix: true
      serviceId: admin
```
I want to add a "pages" service like, and I add before path "/admin/**
```
zuul:
  ignoredServices: '*'
  routes:
    pages:
      path: /admin/pages/**
      stripPrefix: true
      serviceId: pages
    admin:
      path: /admin/**
      stripPrefix: true
      serviceId: admin
```
And POST to "http://localhost:8765/refresh"
It seem zuul not reload routes.
And I test, change it into
```
zuul:
  ignoredServices: '*'
  routes:
    admin:
      path: /admin/**
      stripPrefix: true
      serviceId: admin
    pages:
      path: /bla/pages/**
      stripPrefix: true
      serviceId: pages
```
Amazing, it works. Please tell me why doesn't it work if I add it before first routes
I must restart zuul, first case must work
