### ISSUE TITLE
spring.cloud.config.uri is no longer fetched from the active Spring profile, starting with v4.0.3

### ISSUE THREAD

**Issue by magnus-larsson** [spring-cloud/spring-cloud-config#2765]
**Describe the bug**

Starting with Spring Cloud Config 4.0.3, Spring profile-specific settings of `spring.cloud.config.uri` are ignored.

**Sample**

To reproduce the problem, follow these steps:

1. Checkout Spring Cloud Config v4.0.2

```
git clone https://github.com/spring-cloud/spring-cloud-config.git
cd spring-cloud-config
git checkout v4.0.2
```

2. Start the sample config server:

```
cd spring-cloud-config-server
../mvnw spring-boot:run
```

3. In a separate terminal, verify that the config server works

```
curl localhost:8888/foo/development -s | jq
```

4. Remove all property files in the folder `spring-cloud-config-sample/src/main/resources` and add `application.yml` with the following content:

```
spring.config.import: "configserver:"

spring.application.name: bar
spring.cloud.config.uri: http://configserver:8888/

---
spring.config.activate.on-profile: localtest

spring.cloud.config.uri: http://localhost:8888/
```

5. Start the sample config client, using the Spring profile `localtest`:

```
cd spring-cloud-config-sample
SPRING_PROFILES_ACTIVE=localtest ../mvnw spring-boot:run
```

6.  In a separate terminal, verify that the sample config client works

```
curl "localhost:8080/?q=foo"
# Expect the response: "bar2"

# Stop the config-client
CTRL/C
```

**Note:** This proves that the config client picks up `spring.cloud.config.uri` (http://localhost:8888/) from the active profile, `localtest`!

7. Checkout v4.0.3 and rerun the tests of the sample config client:

```
git checkout v4.0.3
SPRING_PROFILES_ACTIVE=localtest ../mvnw spring-boot:run
```

**Note:** The config client will now fail with the error: `Caused by: java.net.UnknownHostException: configserver`, since it ignores the setting `SPRING_PROFILES_ACTIVE=localtest`

**Note:** As a workaround, the explicit URL to the config serfver can be specified when starting the config client:

```
SPRING_CLOUD_CONFIG_URI=http://localhost:8888 SPRING_PROFILES_ACTIVE=localtest ../mvnw spring-boot:run
```

**Comment by ryanjbaxter** [comment]
The version of Spring Cloud you are using is no longer supported.  Can you please and try and reproduce this problem with Spring Cloud 2023.0.5 or Spring Cloud 2024.0.0?

**Comment by magnus-larsson** [comment]
Yes! 

I'm sorry for being unclear. I intended to show in which version the issue was introduced, i.e., v4.0.3.

I failed to mention that the error remains in the main branch.

To verify for Spring Cloud 2023.0.5 and Spring Cloud 2024.0.0, replace `git checkout v4.0.3` in the instruction above with `git checkout v4.1.5` and `git checkout v4.2.0`.

**Comment by ryanjbaxter** [comment]
I am not entirely sure what. might be happening here but your configuration is invalid so I wouldn't be surprised there is unexpected behavior.

You cannot mix the use of `spring.config.import` and `spring.cloud.config.uri` you should be using one approach or the other.

If you want to use `spring.cloud.config.uri` then you need to either include `spring-cloud-starter-bootstrap` on the classpath or set `spring.cloud.bootstrap.enabled=true` as a system or environment variable.  In addition you need to set `spring.cloud.config.uri` in `bootstrap.yaml | properties`.  In this case there is no need to set `spring.config.import`.

If you are using `spring.config.import` then none of the above is needed.  However there are some "gotchas" when it comes to using `spring.config.import` and profiles.  The main one you will run into in this situation is that `spring.config.import` is not overriden like other properties would be when using profiles.  For example if you did this:

```
spring.application.name: client
server.port: 9090
spring:
  config:
    import: "configserver:http://configserver:8888"

---
spring:
  config:
    activate.on-profile: localtest
    import: "configserver:http://localhost:8888"
```

The application would still reach out to the config server at `configserver:8888` because when boot initially loads configuration it has no idea about the configuration thats is activated in `localtest` because Spring Boot loads all configuration without any active profiles first.  After doing that it then loads all configuration from all active profiles at which point it will come across the profile specific `spring.config.import` and load configuration from those statements as well.

So what you need to do instead is this:

```
spring.application.name: client
#spring.cloud.config.uri=http://configerver:8888/
server.port: 9090
spring:
  config:
    import: "optional:configserver:http://configserver:8888"

---
spring:
  config:
    activate.on-profile: localtest
    import: "configserver:http://localhost:8888"

```

By making the first `spring.config.import` optional it fill fail and then allow the application to continue.

**Comment by magnus-larsson** [comment]
Thanks, Ryan!

I was apparently working with a halfway migration over to using `spring.config.import` that worked, by coincidence, up until v4.0.2!

My example now works fine on the `main` branch using the following configuration:

```
spring.application.name: bar
spring.config.import: "optional:configserver:http://configserver:8888"

---
spring.config:
  activate.on-profile: localtest
  import: "configserver:http://localhost:8888"
```
