### ISSUE TITLE
How to config  logging pattern?

### ISSUE THREAD

**Issue by Dreampie** [spring-cloud/spring-cloud-config#284]
```yml
logging:
  level:
    ROOT: INFO
  console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger - %msg%n'
  file: './logs/${spring.application.name}.%d{yyyy-MM-dd}.log'

```
