### ISSUE TITLE
Examples showing outdated code

### ISSUE THREAD

**Issue by SaudKadiri** [spring-cloud/spring-cloud-config#2841]
**Issue**:
The [spring-cloud-config-sample](https://github.com/spring-cloud/spring-cloud-config/tree/main/spring-cloud-config-sample/src/main/resources) still uses `bootstrap.yml` which is a legacy practice, and `application.yml` should be used instead (Spring 2.4+)

Thus we also get an error currently:
![Image](https://github.com/user-attachments/assets/60109451-1f23-452a-9d52-a8cdbdb7f5b0)

**Solution**:
1. Update the example to use `spring.config.import=` in `application.yml` instead
```yaml
spring:
  application:
    name: application
  config:
    import: optional:configserver:http://localhost:8888
```
2. Delete `bootstrap.yml`
3. Now, it's fixed:
![Image](https://github.com/user-attachments/assets/7a4ee13e-9fd7-4944-a506-a62c2a6ac585)

References:
1. [Spring Cloud Config Document](https://docs.spring.io/spring-cloud-config/reference/client.html)
