### ISSUE TITLE
Config Client Fail Fast not working when using Eureka First Bootstrap

### ISSUE THREAD

**Issue by codependent** [spring-cloud/spring-cloud-config#291]
I am working with Spring Cloud Netflix microservices so my service is configured to use Eureka first bootstrap to locate the config server. According to the doc we could configure a fail fast option to prevent the services from starting when the Config Server is not available. 

Apparently this doesn't work with Eureka clients, any reason for it?

bootstrap.yml:
```
spring:
  application:
    name: random-image-microservice
  cloud:
    config:
      discovery:
        enabled: true
    failFast: true
        
server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
```
The failFast property isn't even considered as we can see In `DiscoveryClientConfigServiceBootstrapConfiguration`, where there's only a log.warn:
```
private void refresh() {
		try {
                     ...
        }catch (Exception ex) {
			log.warn("Could not locate configserver via discovery", ex);
		}
```
