### ISSUE TITLE
Serving Plain Text - {profile} ignored

### ISSUE THREAD

**Issue by vsgvsg** [spring-cloud/spring-cloud-config#303]
I am trying to access a plain text config using /{name}/{profile}/{label}/{path} endpoint. My Config Server is configured to have separate repos for each profile:
```
spring:
  cloud:
    config:
      server:
        git:
          uri: http://dunx20:10080/ta/{profile}
          searchPaths: "*"
```
The file is located at `http://dunx20:10080/ta/development/logback.xml`.
When I am trying to access it using this endpoint `http://localhost:8888/booty/development/master/logback.xml` I am getting  
NoRemoteRepositoryException:  http://dunx20:10080/ta/default: http://dunx20:10080/ta/default/info/refs?service=git-upload-pack not found

One thing I've noticed is that in org.springframework.cloud.config.server.resource.GenericResourceRepository the profile name is hardcoded:
```
public synchronized Resource findOne(String application, String profile, String label, String path) {
    String[] locations = this.service.getLocations(application, "default", label).getLocations();
``` 
 I am using `Brixton.BUILD-SNAPSHOT`.
