### ISSUE TITLE
Failed to walk directory: \\C\Users\user\git\config-repo

### ISSUE THREAD

**Issue by cforce** [spring-cloud/spring-cloud-config#308]
I get following error for a local git repo using the monitor feature.
with cfg: 
```yml
spring: 
  profiles: default,local,native

  cloud: 
    config: 
      server: 
        native: 
          searchLocations: "[file://${user.home}/dev-cfg-folder]"
        git: 
          cloneOnStart: true
          basedir: target/config
          uri: file://${user.home}/git/config-repo

```
2015-12-18 15:39:03,985 ERROR org.springframework.cloud.config.monitor.FileMonitorConfiguration (FileMonitorConfiguration.java:291) - Failed to walk directory: \\C\Users\user\git\config-repo
