### ISSUE TITLE
Maps with Strings containing periods as keys are not interpreted correctly

### ISSUE THREAD

**Issue by tburch** [spring-cloud/spring-cloud-config#317]
It seems that if you have the following yml config, which has a Map that uses Strings with a period as the key, the map is incorrectly parsed and is not returned properly. Here's the yml I'm using:
```
---
wordsToNumbers:
  "one.two": 1.2
  "three.four.five": 3.45
  "zero": 0
```
The resulting config when requesting the yml from the config server is:
```
wordsToNumbers:
  one:
    two: 1.2
  three:
    four:
      five: 3.45
  zero: 0
```
I'm expecting the keys to still be Strings instead of interpreting the `.` as a child object in the key.
