### ISSUE TITLE
Support placeholders for searchPaths on remote repos

### ISSUE THREAD

**Issue by superfly72** [spring-cloud/spring-cloud-config#328]
To support a more flexible Git repo structure it would be good if the {placeholder} support was supported in the searchPaths option. 
Ideally we should be able to support having a single repo with config store under application (and profile) structure. Current implementation requires change to the searchPaths entry on the config server whenever a new application is added.

```
spring:
  cloud:
    config:
      server:
        git:
          uri: https://xxxx/config-repo.git
          searchPaths: {application}
```

**Comment by superfly72** [comment]
I've tried this with 1.1.0.M5 but doesn't seem to work with either https or ssh git repo's.

(application.yml)
```
spring:
  cloud:
    config:
      server:
        git:
          #uri: ssh://xxxxx:7999/mic/cloudconfig.git
          uri: https://xxxxxx/scm/mic/cloudconfig.git
          cloneOnStart: true
          searchPaths: {application}
```


```
(cloudconfig repo)
├── application.properties
├── application.yml
└── demo-app
    ├── demo-app-dev.yml
    ├── demo-app-prod.yml
    ├── demo-app.yml
    ├── devcloud.js
    └── simple.conf
```

Test - use URL: http://localhost:8888/demo-app/dev

Expected result: 3 resource files returned (application.properties, application.yml, demo-app-dev.yml)
Actual result: 2 resource files returned (application.properties, application.yml)

**Comment by dsyer** [comment]
Works for me. You need to quote the search paths value in YAML ("{" is not a valid literal). Maybe that's the problem?

**Comment by superfly72** [comment]
quoting in the yaml file fixed my issue. Thanks.

```
spring:
  cloud:
    config:
      server:
        git:
          #uri: ssh://xxxxx:7999/mic/cloudconfig.git
          uri: https://xxxxxx/scm/mic/cloudconfig.git
          cloneOnStart: true
          searchPaths: "{application}"
```
