### ISSUE TITLE
Loading multiple Git Repos at the same time

### ISSUE THREAD

**Issue by marcellodesales** [spring-cloud/spring-cloud-config#383]
Hi there, we have a requirement to load settings in different layers... 

Shared Properties
----

* Shared settings for all Services: 
 * Config Git Repo: `github.com/service/shared-config`
 * application.properties: All the general properties shared across 
 * Core capability team can change settings at any time, and work independently.

Service X
-----

* Service X: Must load its own properties plus the Shared.
 * Config Git Repo: `github.com/service/x-config`
 * x.properties
 * x-qa.properties
 * X capability team can work on their own properties isolated, but inherit, reuse and override the core capabilities.

Service Y
-----

* Service Y: Must load its own properties plus the Shared.
 * Config Git Repo: `github.com/service/y-config`
 * application.properties
 * y.yaml
 * Y capability team can work on their own properties isolated, but inherit, reuse and override the core capabilities.

Desired Behavior
-------

* Is it possible that the server could return all properties across different git repos for a given `${application}/{$profile}` combo? 

* My desired behavior is that the call to the `x/qa` combo would return the following:

```json
$ curl localhost:8888/x/qa
{
   "name":"application",
   "profiles":[
      "qa"
   ],
   "label":"master",
   "propertySources":[
      {
         "name":"git@github.com:service/x-config.git/x-qa.properties",
         "source":{
            "app.color":"red",
            "env":"qa",
            "total":"nice"
         }
      },
      {
         "name":"git@github.com:service/x-config.git/x.properties",
         "source":{
            "app.color":"red",
            "total":"nice"
         }
      },
      {
         "name":"git@github.com:service/shared-config.git/application.properties",
         "source":{
            "app.color":"blue",
            "app.enabled":"true"
         }
      }
   ]
}
```

* Similarly, a call to the Y application would result in the following:

```json
$ curl localhost:8888/y/default
{
   "name":"application",
   "profiles":[
      "qa"
   ],
   "label":"master",
   "propertySources":[
      {
         "name":"git@github.com:service/y-config.git/y.yaml",
         "source":{
            "app.color":"blue",
            "env":"default"
         }
      },
      {
         "name":"git@github.com:service/y-config.git/application.properties",
         "source":{
            "total":"cool",
            "app.enabled":"false"
         }
      },
      {
         "name":"git@github.com:service/shared-config.git/application.properties",
         "source":{
            "app.color":"blue",
            "app.enabled":"true"
         }
      }
   ]
}
```

**Comment by dsyer** [comment]
Isn't that what you get when you set `spring.cloud.config.server.git.searchPaths=/{application}`?

**Comment by marcellodesales** [comment]
Hi @dsyer, actually that did not work... It is returning only the application that I have requested... Here's the configuration:

Server Config
-----

```yml
$ cat server-config/application-multi-repo.yml 
info:
  component: Config Server
spring:
  application:
    name: configserver
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        git:
          searchPaths: /{application}
          uri: git@github.com:marcellodesales/ctg-config.git
          repos:
            ttu: git@github.com:marcellodesales/ttu-config.git
            dancing: git@github.com:marcellodesales/dancing-bear-config.git
management:
  context_path: /admin
```

Default application: Makes sense
-----

```json
$ curl http://localhost:8888/application/default | jq
{
  "name": "application",
  "profiles": [
    "default"
  ],
  "label": "master",
  "propertySources": [
    {
      "name": "git@github.com:marcellodesales/ctg-config.git/application.properties",
      "source": {
        "zero": "false"
      }
    }
  ]
}
```

TTU application: I expected `application.properties` to be loaded
-----

* As per the requirements above, I expected that application.properties were also loaded, being the default from the `"global"` git repository. However, only the file from the app's directory.

```json
$ curl http://localhost:8888/ttu/default | jq
{
  "name": "ttu",
  "profiles": [
    "default"
  ],
  "label": "master",
  "propertySources": [
    {
      "name": "git@github.com:marcellodesales/ttu-config.git/ttu.yml",
      "source": {
        "a": "b"
      }
    }
  ]
}
```

Questions
----

* Is the configuration correct?
* Am I missing anything?
* Where should I change if I need to submit a PR, if this requirement makes sense?

**Comment by dsyer** [comment]
I see. So this is a duplicate of #286. Thanks for the clarification. To add this feature would be slightly disruptive because you would have to change the way that the multi repo repository searches for locations. Have a go if you want though.

**Comment by dragontree101** [comment]
@marcellodesales could you slove this problem in same repo? 
if yes , how can i config my server? thanks

**Comment by marcellodesales** [comment]
@dragontree101 Yeah, with a single repo that's simpler...

Server Config
----

Start a config server with the following config... For instance, two teams: `ttu` and `dancing` in the search paths.

```yml
info:
  component: Config Server
spring:
  application:
    name: configserver
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        git:
          uri: git@github.company.com:org/config-repo.git
          searchPaths: ttu,dancing
          
management:
  context_path: /admin
```

Git Repo: Root Structure
----

* application.properties or application.yml works are global config

![screen shot 2016-05-25 at 2 34 12 pm](https://cloud.githubusercontent.com/assets/131457/15557136/3a61994e-2286-11e6-8497-fd2098e7c92a.png)

Git Repo: search Paths
-----

* Define the app with the same name, and the profiles you need...
* `ttu` app
* teams: `ttu-android`, `ttu-ios`

![screen shot 2016-05-25 at 2 34 27 pm](https://cloud.githubusercontent.com/assets/131457/15557151/56236cac-2286-11e6-8125-9be89f807cef.png)

Note tha there's a directory called `ios`, but that does not work...
