### ISSUE TITLE
Support {cipher}{key:testkey} prefixed ciphers when spring.cloud.config.server.bootstrap=true

### ISSUE THREAD

**Issue by bitsofinfo** [spring-cloud/spring-cloud-config#434]
Support `{cipher}{key:testkey}` prefixed ciphers when `spring.cloud.config.server.bootstrap=true`

When I had my config server, configured with `bootstrap.yml` as follows (for the config server itself to get its configs from git), ciphers (with a key alias specified) stored in the remote config-server.yml file in Git failed to be decrypted.

```
spring.cloud.config.server.bootstrap: true
spring.application.name: my-config-server
spring.cloud.config.server.git.uri: ${my.git.url}

encrypt:
  keyStore:
    location: ${my.keystore.resource_location}
    password: ${my.keystore.store_pass}
    alias: ${my.keystore.default_key_alias}
    secret: ${my.keystore.default_key_secret}
```

Git remote config file: my-config-server.yml

FAILED: `my.crypted.prop: '{cipher}{key:myAlias}xxxxxxxx...'`

WORKS: `my.crypted.prop: '{cipher}xxxxxxxx...'`

The solution was to add the following in `spring.factories`

```
org.springframework.cloud.bootstrap.BootstrapConfiguration=org.springframework.cloud.config.server.config.EncryptionAutoConfiguration
```

See conversation here: https://gitter.im/spring-cloud/spring-cloud?at=5772de1d8441a8124d7a4aa7
