### ISSUE TITLE
Client side support for decryption of {cipher}{key:testkey} prefixed ciphers

### ISSUE THREAD

**Issue by rlynch** [spring-cloud/spring-cloud-config#448]
As documented at http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_serving_encrypted_properties support for client side decryption is supported.  However, I am unable to use an encrypted property which contains a key prefix as documented at http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_using_multiple_keys_and_key_rotation

Here is my setup.  I have a spring cloud config server running 1.1.2.  It has encryption disabled via the property....

```
spring.cloud.config.server.encrypt.enabled=false
```

My client side bootstrap.yml looks like this.

```
spring:
  application:
    name: config_test_server_config

encrypt:
  keyStore:
    location: classpath:/sccsTestKeyStore.jks
    password: letmein
    alias: sccsTestKey
    secret: changeme
```

When using a key prefix the decryption fails but when removing the prefix it works.
FAILED:  my.crypted.prop: '{cipher}{key:sccsTestKey}xxxxxxxx...'
WORKS: my.crypted.prop: '{cipher}xxxxxxxx...'

This is almost exactly the same problem as https://github.com/spring-cloud/spring-cloud-config/issues/434 where key prefixes don't work on the server.  434 does have a workaround documented in which you create a spring.factories file with the following entry.

`#org.springframework.cloud.bootstrap.BootstrapConfiguration=org.springframework.cloud.config.server.config.EncryptionAutoConfiguration`

I was able to validate this works for my use case when doing server side decryption but this doesn't work on the client side because the EncryptionAutoConfiguration (and other supporting key prefix classes) class is in the spring-cloud-config-server jar and therefor is not available to the client.
