### ISSUE TITLE
basedir property defined in configuration file ignored when instantiating a new JGitEnvironmentRepository

### ISSUE THREAD

**Issue by RaphC** [spring-cloud/spring-cloud-config#451]
Hi,

I'm facing an issue about the use of spring.cloud.config.server.git.basedir. I have a configServer with MultipleJGitEnvironment 

```
       git:
          # repo par defaut
          # Attention le ssh://.... n'est pas supporte.
          uri: <username>@<host>:ST/{application}.git
          # repertoire dans lequel sont clonés les repos
          basedir: '${HOME}/my-git-repo'
```

When I fetch a configuration for an application (e.g : http://host:port/toto/dev/), the config server retrieves the correct configuration files from the git repository and returns the expected result. I noticed, even if I set basedir value , the config server clones my git repository by using the temp dir /tmp/config-repo-random_id.

After some investigation I found when the bean instance of MultipleJGitEnvironmentRepository load a configuration for the first time (the condition !this.placeholders.containsKey(key) is true) it instantiate a new JGitEnvironmentRepository instance, copy all properties from the source, set the uri passed in parameter and overwrite basedir by the default (tmp/config-repo-random_id) instead of using the value set in my bootstrap.cfg (and correctly set in the source which is my MultipleJGitEnvironmentRepository instance).

```
    private JGitEnvironmentRepository getRepository(JGitEnvironmentRepository repository,
            String application, String profile, String label) {
        if (!repository.getUri().contains("{")) {
            return repository;
        }
        ..........
        if (!this.placeholders.containsKey(key)) {
            this.placeholders.put(key, getRepository(repository, key));
        }
        ........
    }

    private JGitEnvironmentRepository getRepository(JGitEnvironmentRepository source,
            String uri) {
        JGitEnvironmentRepository repository = new JGitEnvironmentRepository(null);
        File basedir = repository.getBasedir();
        BeanUtils.copyProperties(source, repository);
        repository.setUri(uri);
        repository.setBasedir(basedir);
        return repository;
    }

```

Am I misunderstand the use of basedir property? 

Thanks

Regards,

**Comment by cazpr** [comment]
I'm trying out spring-cloud-config-server 1.2.0.RELEASE and I'm experiencing the same issue.  This is the configuration I'm using:
```
spring.cloud.config.server:
  git:
    # by default each application has it's own config repo
    basedir: /paht/to/workdir
    uri: ssh://my-server.com/{application}-config.git
    repos:
      # but some applications share the same config repo for convenience 
      group-x:
        pattern: group-x-*/*,*-group-x/*
        uri: ssh://my-server.com/group-x-config.git
```

As already mentioned, it appears that `MultipleJGitEnvironmentRepository` overrides the configured basedir with the temporary folder created in `AbstractScmAccessor`.  In a way this makes sense as it would otherwise use the same directory for multiple folders (I didn't spot any code that creates subfolders in the configured basedir per repo), but it's not really what you'd expect...
