### ISSUE TITLE
spring-cloud-config-client: Decrypt function being run on all {cipher} values in bootstrap.yml even if overridden by a different profile

### ISSUE THREAD

**Issue by PseudoCoding** [spring-cloud/spring-cloud-config#458]
Found an issue today with {cipher} in bootstrap.yml

The class which is calling the decrypt function on values tagged with {cipher} is executing regardless of if the value is overridden or not. I have a bootstrap.yml file similar to below where the encryption methods are different in prod versus non-prod. I get a startup failure stating it could not decrypt the password. Upon debugging for a while we found if you do not have a {cipher} value in the default profile, then it works. I have provided an example of this below.

Broken bootstrap.yml

```
spring:
  application:
    name: api

password: '{cipher}<encypted_password1>'

encrypt:
  key: random_key_a

---

spring:
  profiles: prod

password: '{cipher}<encypted_password2>'

encrypt:
  key: random_key_b
```

Working bootstrap.yml

```
spring:
  application:
    name: api

encrypt:
  key: random_key_a

---

spring:
  profiles: local

password: '{cipher}<encypted_password1>'

---

spring:
  profiles: dev

password: '{cipher}<encypted_password1>'

---

spring:
  profiles: stage

password: '{cipher}<encypted_password1>'

---

spring:
  profiles: prod

password: '{cipher}<encypted_password2>'

encrypt:
  key: random_key_b
```

I believe the issue resides in org.springframework.cloud.config.server.encryption.[CipherEnvironmentEncryptor](https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/encryption/CipherEnvironmentEncryptor.java):72-75

```
value = encryptor.locate(
   this.helper.getEncryptorKeys(name, StringUtils
      .arrayToCommaDelimitedString(environment
         .getProfiles()), value)).decrypt(this.helper.stripPrefix(value));
```

**Comment by ryanjbaxter** [comment]
Just to make sure I understand the issue, you are not expecting that the `password` property in the default profile would be decrypted because it is overriden in the `prod` profile, right?

**Comment by dphoude** [comment]
That is correct. The issue is caused by the fact that prod uses a different encryption keystore than any of the other environments so in prod it tried to decrypt the default profile with the prod keystore which clearly will not work.

**Comment by ryanjbaxter** [comment]
In trying to reproduce the problem I found that if you move the `password` properties to `application.yml` that it worked fine.  Not sure as to why off the top of my head, could be that things in `bootstrap.yml` are being decrypted earlier on.

Here is what my `bootstrap.yml` looks like 
```
encrypt:
  key: random_key_a

---

spring:
  profiles: prod

encrypt:
  key: random_key_b
```

Here is my `application.yml`
```
spring:
  application:
    name: api
  cloud:
    config:
      server:
        git:
          uri: file:///Users/ryanjbaxter/temp/tempconfigrepo
server:
  port: 8888


password: '\{cipher}f4f9feffc59e488cddc95ab295d91d0041c6d9c9ff1a5c740204327cb6c834c9'

#encrypt:
#  key: random_key_a

---

spring:
  profiles: prod

password: '\{cipher}c135afdd762a196878dbe8077101661b03c11cc0007d9569cbe060ea0f789de8'

#encrypt:
#  key: random_key_b

spring:
  application:
    name: api
  cloud:
    config:
      server:
        git:
          uri: file:///Users/ryanjbaxter/temp/tempconfigrepo
server:
  port: 8888


password: '\{cipher}f4f9feffc59e488cddc95ab295d91d0041c6d9c9ff1a5c740204327cb6c834c9'

#encrypt:
#  key: random_key_a

---

spring:
  profiles: prod

password: '\{cipher}c135afdd762a196878dbe8077101661b03c11cc0007d9569cbe060ea0f789de8'

#encrypt:
#  key: random_key_b
spring:
  application:
    name: api
  cloud:
    config:
      server:
        git:
          uri: file:///Users/ryanjbaxter/temp/tempconfigrepo
server:
  port: 8888


password: '\{cipher}f4f9feffc59e488cddc95ab295d91d0041c6d9c9ff1a5c740204327cb6c834c9'

#encrypt:
#  key: random_key_a

---

spring:
  profiles: prod

password: '\{cipher}c135afdd762a196878dbe8077101661b03c11cc0007d9569cbe060ea0f789de8'

#encrypt:
#  key: random_key_b
spring:
  application:
    name: api
  cloud:
    config:
      server:
        git:
          uri: file:///Users/ryanjbaxter/temp/tempconfigrepo
server:
  port: 8888


password: '\{cipher}f4f9feffc59e488cddc95ab295d91d0041c6d9c9ff1a5c740204327cb6c834c9'

---

spring:
  profiles: prod

password: '\{cipher}c135afdd762a196878dbe8077101661b03c11cc0007d9569cbe060ea0f789de8'

```

Can you give that a shot and see if it fixes the problem?

**Comment by dphoude** [comment]
You are correct, it works fine in an application.yml. The problem for us is we are encrypting the password for our spring cloud config server which from my understanding has to be in a bootstrap.yml.

**Comment by ryanjbaxter** [comment]
so are your using Spring Security and just using basic auth to secure your config server?  Are you setting `security.user.password`?

**Comment by dphoude** [comment]
Yes that is correct

**Comment by poznachowski** [comment]
I think I have the same problem. My bootstrap is as follows:
```
spring:
  application:
    name: app
---

spring:
  profiles: '!local'
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      username: user
      password: '{cipher}xxx'

---

spring:
  profiles: local
  cloud:
    config:
      enabled: false
```
I can't run my integration tests with `local` profile (of course with no `encrypt.key` property), as it still tries to decrypt the `spring.cloud.config.password`. It won't work even if a add some meaningless, but not encrypted password in local configuration.
