### ISSUE TITLE
Spring Cloud Config don't accept null values

### ISSUE THREAD

**Issue by zetta** [spring-cloud/spring-cloud-config#459]
I have this config
```yml
assets:
    baseurl: http://example.com/
    version: SNAPSHOT
    a:
        version: ~
    b:
        version: v2.3
    c:
        version: v2.3
```

I want to have null values on some configs so if I found that null values I can fallback to the previous value in the hierarchy, but when I have null values on my `yml` file Spring Cloud Server always returns a 500 error code.

```
Class: java.lang.NullPointerException
Message: null
```

```
    Line | Method
->> 1142 | runWorker in java.util.concurrent.ThreadPoolExecutor
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    617 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . in java.lang.Thread
```
