### ISSUE TITLE
Can spring cloud config merge arrays from different property sources into a single one?

### ISSUE THREAD

**Issue by soiff** [spring-cloud/spring-cloud-config#460]
As I mentioned in the title.

Typically, I got several configurations, for example `one.yml` and `two.yml`, both defined key `rpc.consumers`, which is an array of objects.

For example:

```
# one.yml
rpc:
  consumers:
    - type: a.b.c.Consumer0
```

```
# two.yml
rpc:
  consumers:
    - type: x.y.z.Consumer0
```

Actually, I need merge these two arrays into a single one, could spring cloud config achieve this?
