### ISSUE TITLE
can i get config in ApplicationListener

### ISSUE THREAD

**Issue by dragontree101** [spring-cloud/spring-cloud-config#493]
i put my config file in git, i can get config from my app seems config in my local
but if i want to get config in 
```
ApplicationStartedEventListener implements ApplicationListener<ApplicationEnvironmentPreparedEvent> {

  public void onApplicationEvent(
      ApplicationEnvironmentPreparedEvent applicationEnvironmentPreparedEvent) {
  ConfigurableEnvironment env  =  applicationEnvironmentPreparedEvent.getEnvironment()
  }
```

i don't get config from gitlab, how can i get config in onApplicationEvent() method?

in onApplicationEvent() i only get what i write in my bootstrap-test.yaml file
```
spring:
  profiles: production
  application:
    name: push
  cloud:
    config:
      uri: http://127.0.0.1:8888/
      username: admin
      password: 123456
      label: master
```
