### ISSUE TITLE
Config Client is not decrypting the '{cipher}{key:myTestKey}AXRTSADsadasdasd123asd=' value. 

### ISSUE THREAD

**Issue by ankit8051** [spring-cloud/spring-cloud-config#511]
Hi Team,

I have created one config server and added below configuration in application.yml file.

```
encrypt:
  keyStore:
    location: classpath:/server.jks
    password: letmein
    alias: mytestkey
    secret: changeme
```

I have followed the same steps provided by spring cloud config [document](http://cloud.spring.io/spring-cloud-static/spring-cloud-config/1.2.0.RELEASE/#_key_management).

This configuration exposed two end point /encrypt and /decrypt. A am able to encrypt and decrypt the values using these end point.

I have encrypted one of my password using /encrypt end point then stored this value in my repository.
`password:'{cipher}{key:myTestKey}AXRTSADsadasdasd123asd='`

But when I am tried to fetch the value from my config client it is not automatically decrypted. I am getting the '**{cipher}{key:myTestKey}AXRTSADsadasdasd123asd=**' the same value as I have configured in my repository.

My config client application's bootstrap.yml has below configuration.

```
encrypt:
  keyStore:
    location: classpath:/server.jks
    password: letmein
    alias: mytestkey
    secret: changeme
```

Please team guide  me on this. I need decryption happned on client side. 

Thanks in advance.
