### ISSUE TITLE
discovery data for config server never updates after startup

### ISSUE THREAD

**Issue by whboyd** [spring-cloud/spring-cloud-config#514]
It appears that in discovery-first mode, the config client is not updating its location information for the config server when that data changes in eureka (i.e. when a config server instance is removed or added in eureka). Is this currently expected behavior, or am I doing something wrong?

```
spring:
    cloud:
        config:
            enabled: true
            failFast: true
            discovery:
                enabled: true
eureka:
    client:
        serviceUrl:
            defaultZone: [[my eureka defaultZone]]
```

When I take down the first config server instance, the configserver healthcheck in the app begins to fail despite there being a separate working node. The same occurs if I restart the config server node with a new password in the eureka metadataMap, in which case the client keeps trying to use the old password.
