### ISSUE TITLE
Changes in local filesystem are not being broadcasted

### ISSUE THREAD

**Issue by Syy0n** [spring-cloud/spring-cloud-config#542]
I use the following configuration for my spring config server:
```
spring:
  profiles:
    active: native
  application:
    name: cloudconfig
  cloud:
    config:
      server:
        native:
          search-locations: file:${user.home}/localrepo
```
Is there any way to broadcast the changes in the local configuration files to the clients? For example when i would like to add a new route to the zuul's config file.
