### ISSUE TITLE
Git SSH Deployment keys as alternative to username/password

### ISSUE THREAD

**Issue by Vad1mo** [spring-cloud/spring-cloud-config#55]
username/password has the drawback that they a tied to a human or a technical user.
There is also the possibility to access the repository not only with username/password but also with ssh keys. 
Does spring-cloud-config support ssh keys?

**Comment by dsyer** [comment]
See also discussion in #34: my impression from there was since github uses HTTP basic for token authentication it would work anyway with no changes.

@btiernay said in #34 that he was going to open a new ticket and contribute something. So far nothing happened. What would you propose?

**Comment by Vad1mo** [comment]
Thank you Dave. Advantage of SSH Keys vs. OAuth is that this is git standard. I will try out the suggestions mentioned #34 and see how far we get.

**Comment by btiernay** [comment]
@dsyer Sorry for the delay. I got pulled in a different direction and haven't had a chance to tackle this. I plan on coming back to #34 eventually if no one takes it in the meantime. Cheers.

**Comment by ccit-spence** [comment]
Is username/password still working with bitbucket?  Using 'git.uri' https://uname:pwd@bitbucket.org/etc...

**Comment by dsyer** [comment]
It would work if bitbucket supports HTTP basic authentication (JGit handles it AFAIK). Why would it not?

**Comment by ccit-spence** [comment]
I have used it before with Bitbucket, started working on setting up a config server and now getting this error: `Authentication is required but no CredentialsProvider has been registered`

**Comment by ccit-spence** [comment]
To clarify using YAML
    Spring:
        cloud:
            config:
                server:
                    git:
                        uri: `URL HERE`

**Comment by dsyer** [comment]
OK, I guess JGit handles it if you register a handler. I think it's a static method call so you can do it anywhere (from memory). Check the JGit documentation / forums and if you get something working that we can incorporate into this project that's great.

**Comment by ccit-spence** [comment]
Not sure exactly where yet, but I did have it working in 1.0.0.M2  Something must have changed since then.

**Comment by ccit-spence** [comment]
I have verified with M2 it worked.  M3 up to RC2 it fails.  RC1 has the error that I am seeing now.

**Comment by ccit-spence** [comment]
Figured it out.  Nothing needed to change.  I was not injecting the properties the way the environment properties were being read into the `JGitEnvironmentRepository.java` class.

Before:
```
spring:
    cloud:
        config:
            server:
                git:
                    uri: https://username:password@bitbucket.org/xxx/repo.git
```
After:
```
spring:
    cloud:
        config:
            server:
                git:
                    uri: https://bitbucket.org/xxx/repo.git
                    username: someuser
                    password: strongpassword
```
