### ISSUE TITLE
logging.config not taking effect when pulled from remote spring cloud config server

### ISSUE THREAD

**Issue by ulmermark** [spring-cloud/spring-cloud-config#581]
We have applications that utilize a local application.yml ( embedded in the spring boot app jar)  with the following setting in the default profile:

```
logging:
   config:  classpath:logback-spring.xml
```
All works fine when running the default profile.

When we run the application using a profile that runs in 'cloud mode' ( i.e. eureka and config server ( discovered via eureka)) we have a setting of the following in a specific profile in the config server root/application.yml

```
logging:
    config:    ${spn.spring.cloud.config.runtime.uri}/${spring.application.name}/${spring.profiles.active}/${spring.cloud.config.label:master}/logback-spring.xml
```

This extracts the logback config file as plain text from the config server using the proper uri syntax for plain text files from a remote config server ( http://host:port/application/profile/label/logback-spring.xml)

Please ignore ${spn.spring.cloud.config.runtime.uri} as it is a property our application has created via a EnvironmentPostProcessor that identifies the discovered URI of the config server via eureka that has been injected into the Property sources. ( it works...and will return http://localhost:8888, if running everything on the same box) 

It appears that the 'remote' value for logging.config is not used as long as the one in the jar's application.yml / default profile is present.

If we remove the JARs logging.config setting ( and replace with the logging.level... approach for the default profile) , then run a 'cloud' profile, then the remote config server value for logging.config is used and works.

I have stepped through the debugger and see where the logging system is re-initialized after connecting to the remote config server (PropertySourceBootstrapConfiguration)...and property replacement is done on the property logging.config.....but the value in the jar's application.yml takes precedence.

**Comment by ryanjbaxter** [comment]
If you know can come up with a fix that works better (since you know where the problem is an have a test case) would you mind submitting a PR?

**Comment by ulmermark** [comment]
Ryan,

We discovered in our application, that someone had switched some of the override flags so that the config repo values would not override local values...We had to switch them back and then the 'remote' values from the config repo started taking effect.

Those override switches are powerful and best left alone unless you know what your doing.

If I rememeber correctly..someone set the ***overrideNone: true*** which really sent us for a loop when things just stopped working


```
spring:
    profiles: local-cloud,local-docker
    cloud:
      config:
            overrideSystemProperties: false  # allows -D switches on java command line to take effect and not be overwritten by config repo values ( true is the default)
            overrideNone: false # allows for config repo values to override 'local' values ( false is the default)

```
