### ISSUE TITLE
Spring cloud config server - health check is broken when using vault 

### ISSUE THREAD

**Issue by vasilievip** [spring-cloud/spring-cloud-config#610]
When I provide vault token, I'm getting keys from vault and git:
```
curl -X "GET" "http://localhost:8080/myservice.properties" -H "X-Config-Token: 27004d54-f1ac-31eb-572e-7fb1445a6be7"
coupons.setting1: placeholder1.value
placeholder1: placeholder1.value
vaultkey1: secret
```
When I go to health check, I'm getting service down status due to missing token when traversing status of vault repo:
```
"configServer": {
"status": "DOWN",
"repository": {
"application": "app",
"profiles": "default"
},
"error": "java.lang.IllegalArgumentException: Missing required header: X-Config-Token"
},
```

**Comment by spencergibb** [comment]
thanks for the report

**Comment by vasilievip** [comment]
Vault repo has required token from config client. Not sure about design decisions which led to this. Why git integration don't ask config clients for login/password to git repo? 
Would it be acceptable to add some sort of "deafultVaultToken" and, if config client did not provide one, use default instead?

```
VaultEnvironmentRepository.java
...
	String read(String key) {

		String token = request.getHeader(TOKEN_HEADER);
		if (!StringUtils.hasLength(token)) {
			throw new IllegalArgumentException("Missing required header: " + TOKEN_HEADER);
		}
...
```

**Comment by ryanjbaxter** [comment]
If the git repo requires a username and password you can supply that in the configuration
```
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
          username: trolley
          password: strongpassword
```
