### ISSUE TITLE
YAML for composite environment repositories with non-distincts repository types

### ISSUE THREAD

**Issue by glyn** [spring-cloud/spring-cloud-config#616]
Spring Cloud Services (SCS) is looking to piggy-back on the [composite environment repository](http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_environment_repository) support in Spring Cloud Config. SCS config servers are [configured](https://docs.pivotal.io/spring-cloud-services/1-3/config-server/creating-an-instance.html) by passing JSON to `cf create-service`. The JSON syntax is currently equivalent to the YAML syntax supported by Spring Cloud Config.

SCS has customer requirements to compose repositories _of the same type_ (e.g. two git repos)
Currently, composite environment repositories declared in YAML can only compose repositories _of distinct types_ (git, svn, etc.).

It is not desirable for SCS to diverge by adding its own syntax for composite environment repositories with non-distinct repository types. So this issue requests that the YAML support for composite environment repositories be extended to support composing repositories of non-distinct types.

The following syntax is a suggested starting point for a solution:
```
spring:
  cloud:
    config:
      server:
        composite:
          git:
            uri: file:///path/to/git/repo1
            order: 1
          git:
            uri: file:///path/to/git/repo2
            order: 2
```

**Comment by spencergibb** [comment]
Since those keys represented individual configuration beans, and that wouldn't be the case here (since they would need to be created), it might make sense to do something like:

```
spring:
  cloud:
    config:
      server:
        composite:
          -
            uri: file:///path/to/git/repo1
            type: git
          -
            uri: file:///path/to/git/repo2
            type: git
```

**Comment by glyn** [comment]
@spencergibb I like it.

**Comment by spencergibb** [comment]
Since it's a list, order is implied.

**Comment by csterwa** [comment]
@spencergibb Do we have a solution for "composite" with multiple `git` or other backends? How can we come up with a solution in OSS so our usage would not be stepping away from the syntax in OSS?

**Comment by spencergibb** [comment]
We don't have a solution for this yet

**Comment by csterwa** [comment]
After a short exchange with @spencergibb, it looks like the following syntax is what we can agree upon at this time @glyn:

```
spring:
  cloud:
    config:
      server:
        composite:
          -
            uri: file:///path/to/git/repo1
            type: git
          -
            uri: file:///path/to/git/repo2
            type: git
```

**Comment by spencergibb** [comment]
@csterwa I agree it is a draft. Though I don't foresee any problems, I can't guarantee there won't be changes.

**Comment by ryanjbaxter** [comment]
Just to be clear we also want to support something like

```
spring:
  cloud:
    config:
      server:
        composite:
          -
            uri: file:///path/to/git/repo1
            type: git
          -
            uri: file:///path/to/svn/repo
            type: svn
```

Right?

**Comment by spencergibb** [comment]
@ryanjbaxter I wouldn't see what that would be excluded from this. That currently works without this new configuration. This is for an explicit composite, rather than an implicit one when the types are all distinct. So you could have multiple `svn` types here as well (or multiple of any type for that matter).

**Comment by ryanjbaxter** [comment]
It just seems a little confusing to me to have 2 different ways to configure a composite environment.  In one scenario if you want to use 2 backends of the same type, you have the above config.  If you want to use 2 different backends than you need to configure things as they are today.  I would prefer that we continue to support the configuration we have today, but we also support the ability to configure 2 different backend types for this new config syntax as well.  (Unless it ends up being a ton more work)

**Comment by spencergibb** [comment]
I've always assumed we would keep the original way and this would be a new way.

**Comment by ryanjbaxter** [comment]
Maybe I misunderstood what you were saying above, it sounded like you wouldnt be able to configure backends of different types (git + vault for example) with the new syntax...

**Comment by spencergibb** [comment]
Nope, any combination.

**Comment by spencergibb** [comment]
This new one is just more flexible.

**Comment by georgeharley** [comment]
@spencergibb @ryanjbaxter I've been doing some work on the cloud service broker code that handles `cf create-server` parameters and would value your thoughts on the following slightly more complex YAML example where, for the sake of discussion, an explicit composite is made up of two git backends (one using multiple repos) and a vault backend. Would this be supported by the new syntax discussed above?

```
---
spring:
  cloud:
    config:
      server:
        composite:
        - type: git
          repos:
            development:
              pattern:
              - "*/development"
              - "*/staging"
              uri: https://github.com/development/config-repo
            staging:
              pattern:
              - "*/qa"
              - "*/production"
              uri: https://github.com/staging/config-repo
          uri: https://github.com/spring-cloud-samples/config-repo
        - type: git
          password: pw
          searchPaths: foo, bar
          cloneOnStart: false
          label: branch
          uri: http://example.com/config-repo
          username: user
        - type: vault
          scheme: http
          port: 8200
          host: vault.springapps.io
          backend: secret
          defaultKey: application
          profileSeparator: ","
  profiles:
    active: git,vault
```

**Comment by ryanjbaxter** [comment]
@georgeharley that seems to make sense to me.

**Comment by spencergibb** [comment]
Makes sense. Those are all properties of the `EnvironmentRepository` itself, so it won't be simple to do. As the individual `EnvironmentRepository` is created, each property would need to be manually set on it.

**Comment by sgong0409** [comment]
Hello there, I am wandering is there anyone working on this issue? And will this issue be resolved soon?

**Comment by spencergibb** [comment]
@sgong0409, no one is currently working on it.

**Comment by dmurat** [comment]
Looks like this (or something similar) is already implemented in PCF Spring Cloud Services: http://docs.pivotal.io/spring-cloud-services/1-4/common/config-server/composite-backends.html

**Comment by ryanjbaxter** [comment]
@dmurat yes they have gone ahead and implemented this ontop of the open source code

**Comment by dmurat** [comment]
@ryanjbaxter I can't find related PR. Is it maybe available somewhere else?

**Comment by spencergibb** [comment]
He means they did it in closed source with an eye towards submitting a PR

**Comment by shakuzen** [comment]
Just adding my use case and expressing my interest in this getting implemented. It would be nice if the configuration properties shared by all applications (i.e. in `application.yml`/`application.properties`)  could be controlled in a separate repository from application-specific configuration. With this issue's proposal I'm thinking something like the following might be nice:

```yml
spring:
  cloud:
    config:
      server:
        composite:
          -
            uri: https://github.com/my-org-config/common
            type: git
          -
            uri: https://github.com/my-org-config/{application}
            type: git
```

In this way, the write permissions to the configuration properties that affect all applications can be managed separately, and permissions can be set on each of the individual application-specific configuration repositories.
