### ISSUE TITLE
config-server doesn't get updating from git

### ISSUE THREAD

**Issue by jevel0per** [spring-cloud/spring-cloud-config#629]
i've noticed a strange thing with config-server. when i make a lot of commits  to my local git repository, it stops getting updating. 
by example, i make 20 commits with new settings for microservices and it works fine, but on 21 times config-server doesn't return new data. after that i can make more commits,  but result is the same. it seems like config-server is stuck. When i restart server, it helps, but isn't good for production.

i check setting using http://<ip of config-server>:8888/user/dev/master.

My config is:

```
server:
    port: ${CONFIG_PORT:8888}

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: ...../cloud_service_configs.git
          username: ....
          password: ....

logging:
  config: ${BASEDIR}/logback.xml

```

Config-server version is Brixton.SR6
Spring Boot version is 1.4.2.RELEASE

Is it a bug or did something wrong?
