### ISSUE TITLE
ConfigServerHealthIndicator just verify the label "master"

### ISSUE THREAD

**Issue by roussep** [spring-cloud/spring-cloud-config#638]
In the doHealthCheck from the class `ConfigServerHealthIndicator`, it's not possible to use a different label than "master". 
The last parameter here should be `repository.getLabel()`, not `null`.
`Environment environment = this.environmentRepository.findOne(application, profiles, **null**);`
Otherwise it will always be the default "master".

Here it's my configuration:
```
spring:
  cloud:
    config:
      server:
        health:
          repositories:
            configuration:
              name: configuration.server
              label: poc
```

And I always receive NoSuchLabelException: No such label: master. 
Thanks
