### ISSUE TITLE
Allow custom token name in ConfigServicePropertySourceLocator

### ISSUE THREAD

**Issue by mouellet** [spring-cloud/spring-cloud-config#650]
My config-server is setup behind an API Gateway and registered clients are required to pass an `apikey ` token header but the header name is hard coded in `ConfigClientProperties`.

I need a way to customize the header name, ideally with configuration properties.

**Comment by ryanjbaxter** [comment]
Are you referring to its use in `ConfigServicePropertySourceLocator`?

**Comment by mouellet** [comment]
Yes, in the `getRemoteEnvironment` private method, not in the `VaultEnvironmentRepository`... 

Here is a similar issue in spring-security-oauth (https://github.com/spring-projects/spring-security-oauth/issues/296)

**Comment by spencergibb** [comment]
I'm not sure adding a configurable token name is the right thing to do here. That header name has specific meaning at least in `VaultEnvironmentRepository` and adding an option to change the header name in `ConfigClientProperties` would require a corresponding change on the server side. Maybe using a custom `RestTemplate` with an interceptor would make more sense.

**Comment by mouellet** [comment]
Your right, changing that header name doesn't look like the right thing to do. However, I would really prefer not having to use a custom `RestTemplate` for all my clients...

What about a map of optional headers in the `ConfigClientProperties`? Those could be added to the request in `ConfigServicePropertySourceLocator`.

**Comment by mouellet** [comment]
By adding a `Map` in `ConfigClientProperties`:
```java
private Map<String, String> headers;
```
And adding those properties in the `getRemoteEnvironment` private method of `ConfigServicePropertySourceLocator`:
```java
HttpHeaders headers = new HttpHeaders();
for (Entry<String, String> customHeader : properties.getHeaders().entrySet()) {
    headers.add(customHeader.getKey(), customHeader.getValue());
}
```
Now any client can have custom headers without using a custom `RestTemplate`:
```yaml
spring:
  cloud:
    config:
      headers:
        Authorization: Basic ...
        X-Example-Version: ...
        X-Example-Client-Id: ...
```
The `BasicAuthorizationInterceptor` (and maybe the `GenericAuthorization` interceptor with some logic) could no longer be needed.

I believe this would be the most extensible and developer friendly way to add custom headers to a config client request.

Thoughts?

Thanks!

**Comment by spencergibb** [comment]
Closed via 45336cd

**Comment by dtitov** [comment]
Is this feature implemented? I can't find any docs mentioning:
```yaml
spring:
  cloud:
    config:
      headers:
```
And it's not working for me (`1.5.9.RELEASE`)...

**Comment by spencergibb** [comment]
Yes, "it's not working" doesn't help us much. What is your configuration (and in which file)?

**Comment by dtitov** [comment]
```yaml
spring:
    application:
        name: app-name
    cloud:
        config:
            uri: config-host-name
            username: username
            password: password
            headers:
                X-Hub-Signature: sha1=ae5ae914e70c7d3e22c84b8831b788403a24d8df
    profiles:
        active: development

```
