### ISSUE TITLE
How to use local properties in config client to override remote source?

### ISSUE THREAD

**Issue by zhengl7** [spring-cloud/spring-cloud-config#651]
Help needed on how to correctly have local properties overriding remote property in config client. 

In config server, having

`spring.cloud.config.allowOverride=true` (But looks like this is by default)

In config client, having

`spring.cloud.config.overrideNone=true` (However didn't find any code that shows how this property value on client side is used)

Then in the config server in testapp-testprofile.properties there is

```
propA=valueA
```

I tried to override this with local value in certain config client, and tried to insert 

```
propA=valueB
```
in different files, including 
`bootstrap.properties`
`application.properties` (if any prop is needed and missing from remote source, putting it here would work)
`application-testprofile.properties` (not sure if this is correct).

but none of these works. 

Any pointer to specific code location where the overriding is done would be helpful too, so that I know how to debug.

**Comment by spencergibb** [comment]
Those are only valid for config client (not server)

**Comment by Jeckyli** [comment]
Sorry, can you elaborate a little bit what do you mean by "those"?

I now know one mistake I made, that `spring.cloud.config.overrideNone` is supposed be on server side as well. If this understanding now is correct, I'm wondering how should I introduce the overriding property on the client side?

**Comment by ryanjbaxter** [comment]
The code actually resides in Spring Cloud Commons.  In the properties file on the config server try setting 

```
spring:
    cloud:
        config:
            allowOverride: true
            overrideNone: false
            overrideSystemProperties: false
```

See #359

**Comment by Jeckyli** [comment]
Thanks @ryanjbaxter for replying, but this actually further confuses me. Could you provide a short but complete sample that with the same properties, value on client side override default value from config server? 

Seems that your comments are different than what I understand now, specific questions are,

```
spring:
    cloud:
        config:
            allowOverride: true  //this is default so no need to explicity set right? 
            overrideNone: false  //Isn't this putting value from config server as top priority and ignore any local value from client side? If yes then this is right the opposite I want. 
            overrideSystemProperties: false  //Here does `system properties` include the client local properties like the ones inside client's application.properties? 
```
