### ISSUE TITLE
discovery enable by env

### ISSUE THREAD

**Issue by obeyler** [spring-cloud/spring-cloud-config#685]
I've got two questions: 
1) When I use spring.cloud.config.discovery.enable=true, do I need to use also spring.cloud.config.enabled=true ?

2)Is it possible to use env to configure spring cloud config ?
In this case is it : 
`EUREKA_INSTANCE_METADATA-MAP_CONFIG-PATH=/config`
or 
`EUREKA_INSTANCE_METADATA_MAP_CONFIG_PATH=/config`

 to have the same behavior as in file boostrap.yml like this ?
```
eureka:
  instance:
    metadataMap:
      configPath: /config
```
