### ISSUE TITLE
Could spring cloud config server support multiple git repositories by using placeholder in spring.cloud.config.server.git.uri?

### ISSUE THREAD

**Issue by allenyu5** [spring-cloud/spring-cloud-config#694]
Hi, I wonder if spring cloud config server could support multiple git repositories by using placeholder in spring.cloud.config.server.git.uri.

Here is the case, I have two spring cloud clients, and hope they could connect to one spring cloud config server:
ClientA:
```
spring:
  application:
    name: ClientA
```
ClientB:
```
spring:
  application:
    name: ClientB
```
Server:
```
spring:
  cloud:
    config:
      server:
        git:
          uri: ssh://git@nam.nsroot.net:7199/common/{application}.git
```
At first, set up server, then start ClientA. All work well util now, then I start ClientB, ClientB could not locate right property.

I read doc and know could connect to mutiple git repo like:
```
spring:
  cloud:
    config:
      server:
        git:
          uri: https://git/common/config-repo.git
          force-pull: true
          repos:
            team-a:
                pattern: team-a-*
                uri: http://git/team-a/config-repo.git
                force-pull: true
            team-b:
                pattern: team-b-*
                uri: http://git/team-b/config-repo.git
                force-pull: true
```
But I don't konw application name until client connects to server.
So I wonder if there is a method to use placeholder accessing to mutiple git repo during run time.
Hope for your advice, thank you.
