### ISSUE TITLE
Combine eureka and config server,client cant use discovery

### ISSUE THREAD

**Issue by SixPenny** [spring-cloud/spring-cloud-config#695]
Hi there ,I combined eureka \@EnableEurekaServer and config server \@EnableConfigServer in one class.I also add \@EnableDiscoveryClient annotation on it.But on the register page ,only registry is shown registered,without config-server.When I use config.discovery.enabled=true in client side,an error occurred that 'could not locate PropertySource  and the fail fast property is set,failing'.Is there a method to handle this without split eureke and config server?
### part of server application.yml
```yml
eureka:
    env: prod
    instance:
        hostname: localhost
        appname: registry
        prefer-ip-address: true
    server:
        # see discussion about enable-self-preservation:
        # https://github.com/jhipster/generator-jhipster/issues/3654
        enable-self-preservation: false
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://admin:${security.user.password:admin}@localhost:8761/eureka/
```
### part of client bootstrap.yml
```yml
eureka:
    instance:
        prefer-ip-address: true
    client:
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/

spring:
    cloud:
        config:
            fail-fast: true
            retry:
                initial-interval: 1000
                max-interval: 2000
                max-attempts: 100
#            uri: http://admin:${jhipster.registry.password}@eureka-peer-1:8761/config
            # name of the config server's property source (file.yml) that we want to use
            name: MamsGateway
            profile: prod # profile(s) of the property source
            label: master # toggle to switch to a different version of the configuration as stored in git
            discovery:
                enabled: true
                service-id: config-server
            # it can be set to any label, branch or commit of the config source git repository
```

ps:when I use spring.cloud.config.uri not discovery property ,it can locate config server.
