### ISSUE TITLE
What is the expected property override behavior?

### ISSUE THREAD

**Issue by efenderbosch** [spring-cloud/spring-cloud-config#71]
I checked out https://github.com/spring-cloud-samples/configserver and ran mvn clean spring-boot:run.

When I hit http://localhost:8888/application-docker.yml, one of the resolved properties is

```yaml
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
```

Looking at https://github.com/spring-cloud-samples/config-repo/blob/master/application.yml, I would expect ``eureka.client.serviceUrl.defaultZone`` to resolve to ``http://localhost:8761/eureka/`` in the ``docker`` profile. It seems like the value from the ``cloud`` profile gets set and isn't overriden by the ``docker`` profile. Is my expectation incorrect?
