### ISSUE TITLE
spring.cloud.config.server.git.basedir is ignored

### ISSUE THREAD

**Issue by jogjayr** [spring-cloud/spring-cloud-config#742]
Steps to reproduce:

1. Create a Spring Cloud Config Server application with the configuration:
    
```
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          basedir: "/some/other/directory/here"
          uri: git@example.com:foo/base.git
          repos:
            type1: git@example.com:foo/type1.git
            type2:
              pattern: '*/type2*'
              uri: git@example.com:foo/type2.git
```

2. Run the application

Expected:

`config-repo-*` directories are created under `/some/other/directory/here`

Actual:

`config-repo-*` directories are created under `/private/var/folders/<some other directories/config-repo-*` on Mac OS x

Per http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_version_control_backend_filesystem_use this should work. Unless I have the config wrong somehow
