### ISSUE TITLE
Misleading / wrong error message when setting ignoreLocalSshSettings

### ISSUE THREAD

**Issue by tschmidt01** [spring-cloud/spring-cloud-config#751]
`application.yml:`
```
spring:
  cloud:
    config:
      server:
        git:
          uri: git@bitbucket.domain.com:7999/confserv/config.git
          ignoreLocalSshSettings: true
```
leads to error message on startup:
`Reason: Property 'spring.cloud.config.server.git.hostKey' must be set when 'spring.cloud.config.server.git.hostKeyAlgorithm' is specified`

but should be 
`Reason: [...] must be set when 'spring.cloud.config.server.git.ignoreLocalSshSettings' is specified`
