### ISSUE TITLE
Dynamic Repo provisioning 

### ISSUE THREAD

**Issue by remo408** [spring-cloud/spring-cloud-config#788]
Team,

I wanted to dynamically provide git url's instead of manually adding them i see a provision something like 
```
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/myorg/{application}
```

But that doesn't give me provision to change the entire URI. Should we be able to pass on the git uri in rest body would something like that be possible if so how should do that .

**Comment by ryanjbaxter** [comment]
Can you provide an example of what you are trying to do?

**Comment by remo408** [comment]
I was trying to do something like:

```
spring:
  cloud:
    config:
      server:
        git:
          uri: {git_url}
          username:{git_uname}
          password:{git_pwd}
```
Where i want to provide these as part of my request url:
```
http://localhost:8888/configserver/
body:
{
git_url:""
git_uname:""
git_pwd:""
}
```

**Comment by spencergibb** [comment]
I'm not comfortable sending the whole Ito. URI. Config server is an abstraction and sending in a git URI is leaky, and potentially dangerous.

**Comment by remo408** [comment]
How about the second option where i can point my configserver through bootstrap.yml to a repo with property file that refers to multiple repo's that way i can add repo's dynamically with out restarting the configserver

**Comment by spencergibb** [comment]
the issue you pointed to was implemented 2 years ago if you read further down.

**Comment by remo408** [comment]
so i tried  this:
my bootstrap.yml:
```
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: file:/C:/Users/dev/local/demo/testrepo
```
my testrepo has 
configserver.yml

```
spring:
  cloud:
    config:
      server:
        git:
          repos:
            configserver: https://<url>/scm/testconfigs.git
```

when i do 

`http://localhost:8888/configserver/configserver.properties`

its returnign me

`spring.cloud.config.server.git.repos.configserver: https://<url>/scm/testconfigs.git`

the content from :configserver.yml plz advice, so do i need to follow same process followed in issue #139
