### ISSUE TITLE
MultiRepo Credential support

### ISSUE THREAD

**Issue by remo408** [spring-cloud/spring-cloud-config#796]
Hi how can i use different credentials for different repo's in the following dynamic setup:
```

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/myorg/{application}
```
Appreciate your response
