### ISSUE TITLE
spring cloud config Pattern Matching and Multiple Repositories

### ISSUE THREAD

**Issue by vincent-lee-shi** [spring-cloud/spring-cloud-config#799]
Hello everyone,I refer to the spring cloud to configure this times wrong:
```
cloud:
    config:
      server:
        git:
          uri: https://github.com/vincent-lee-shi/spring-cloud
          repos:
            simple: https://github.com/vincent-lee-shi/simple
            special:
              pattern: special*/dev*,special*/pro*
              uri: https://github.com/vincent-lee-shi/special
```
error:Field error in object 'spring.cloud.config.server.git' on field 'repos[simple]': rejected value [https://github.com/vincent-lee-shi/simple];

But I change it like this, it's normal:
```
config:
      server:
        git:
          uri: https://github.com/vincent-lee-shi/spring-cloud
          repos:
            simple: 
              uri: https://github.com/vincent-lee-shi/simple
            special:
              pattern: special*/dev*,special*/pro*
              uri: https://github.com/vincent-lee-shi/special
```
