### ISSUE TITLE
Per app security?

### ISSUE THREAD

**Issue by bsideup** [spring-cloud/spring-cloud-config#81]
We want to use spring-cloud-config single server for all environments (dev, prod), but dev application shouldn't know anything about prod environment, because it's business critical.

Is it possible to configure security for each app?

For example:
```yaml
spring:
  clound:
    security:
      dev-app:
        user:
          password: "..."
      prod-app:
        user:
          password: "..."
```
