### ISSUE TITLE
providing any value for spring.cloud.config.uri breaks discovery first bootstrap

### ISSUE THREAD

**Issue by brianloss** [spring-cloud/spring-cloud-config#810]
I'm using Dalston.SR3 and want to do discovery first bootstrap for my config server using Consul. My service has a bootstrap.yml with defaults, and then a consul profile that, if enabled, turns on discovery first bootstrap:
```
spring:
  application.name: testservice
  cloud.config:
    discovery.enabled: false
    failFast: true
    uri: '${CONFIG_SERVER_URL:http://configuration:8888}'

---

spring:
  profiles: 'consul'
  cloud.config:
    discovery.enabled: true
``` 
If I remove the `spring.cloud.config.uri` property from my bootstrap.yml, then everything works fine. However, if I leave it there, what I see is that the bootstrap environment discovers the config server URL using the DiscoveryClient, and calls setUri on ConfigClientProperties with the correct URL for the config server.

Then, the servlet environment is initialized and the correct URL is overwritten by the default (`http://configuration:8888` in my example). Further along in initialization, ConfigServicePropertySourceLocator attempts to contact the config server again, but the URL is now invalid and the application fails.

That is, when I have a default value for `spring.cloud.config.uri`, the order of operations is as follows:
1. ConfigClientProperties.setUri (with default value)
2. DiscoveryClientConfigServiceBootstrapConfiguration.refresh
3. ConfigClientProperties.setUri (with discovered URL)
4. ConfigServicePropertySourceLocator.locate (uses discovered URL)
5. ConfigClientProperties.setUri (with default URI overwriting discovered URL)
6. ConfigServicePropertySourceLocator.locate (uses default URL, not discovered URL)

Is there any way around this other than not having a default for `spring.cloud.config.uri`?
