### ISSUE TITLE
spring-cloud-starter is missing spring-security-rsa causing spring-cloud-client to fail to do local decryption

### ISSUE THREAD

**Issue by BoomerBrian** [spring-cloud/spring-cloud-config#84]
I am having a hard time getting {cipher} to work correctly with a configserver and a boot app that is using the config server. Here are some examples.

App A - Spring Boot Config Server
App B - Spring Boot app using the Config Server

configserver (App A) application.yml

```
security:
  user:
    password: '{cipher}7c2205ca988edf017eb1797f082efa22525f51e55cd14a9e683d7affc2ce064c'
```

boot app (App B) bootstrap.yml (Note: I have also tried this in the application.yml as well)

```
spring:
  profiles: dev
  cloud:
    config:
      uri: http://localhost:8888
      username: user
      password: '{cipher}7c2205ca988edf017eb1797f082efa22525f51e55cd14a9e683d7affc2ce064c'
```

When I start up App B I get the following error: (Note: I can access and authenticate in a browser to view this config)

`GET request for "http://localhost:8888/LoadBalancerService/dev/master" resulted in 401 (Unauthorized); invoking error handler`

If I move the security.user.password to the bootstrap.yml in the Config Server then App B will work however the password becomes {cipher}7c2205ca988edf017eb1797f082efa22525f51e55cd14a9e683d7affc2ce064c

This means if I authenticate in a browser the password is {cipher}7c2205ca988edf017eb1797f082efa22525f51e55cd14a9e683d7affc2ce064c

Is this a bug or am I missing something?
