### ISSUE TITLE
No longer possible to set spring.cloud.config.uri as environment variable

### ISSUE THREAD

**Issue by Juliet-Unsilo** [spring-cloud/spring-cloud-config#842]
I have an example project with the following bootstrap file:

```
spring:
  application:
    name: example
  cloud:
    config:
      failFast: true
```
I have the following environment variable: spring.cloud.config.uri=http://localhost:9100

The spring.cloud.config.uri, which is set as an environment variable is ignored, instead the default is used: http://localhost:8888

Note: The same setup works using spring.cloud version Dalston.SR4 together with spring boot version 1.5.8.release

[demo-new.zip](https://github.com/spring-cloud/spring-cloud-config/files/1450305/demo-new.zip)

I think there is a general problem with configuration.
