### ISSUE TITLE
manifest.yml does not override application.yml

### ISSUE THREAD

**Issue by sdesa** [spring-cloud/spring-cloud-config#916]
I am deploying a simple application to PCF and having issues with spring profile overrides. Specific versions used:

Spring Cloud Dependencies: Edgware.SR2
Spring Cloud Services Dependencies (PCF): 1.6.1.RELEASE
Spring Boot Version: 1.5.10.RELEASE

**Issue:**

I have an application.yml with the following content:
```
spring:
  application:
    name: myapp
my:
  url: example.com
```

I created **myapp-dev.yml, myapp-test.yml, myapp-prod.yml** which have overrides for **my.url**

eg: in test

```
my:
  url: example-test.com

```

I am using different manifests for different environments like **manifest.yml**, **manifest-dev.yml**, **manifest-test.yml**, etc which have the following content (eg: **manifest-test.yml** below):
```
---
applications:
 - name: myapp
    env:
      SPRING_PROFILES_ACTIVE: test
```
with the hope that config server serves **my.url** from **myapp-test.yml** when I push the application to PCF with the relevant manifest, since config server takes a higher priority. The profile shows as **[test, cloud]** in the logs but when I access the property with **@value** from a rest controller or access /env endpoint, it still pulls the url from the **application.yml** and does not override it.
