### ISSUE TITLE
configure zuul to use eureka serviceId instead of URL

### ISSUE THREAD

**Issue by sdesa** [spring-cloud/spring-cloud-config#920]
I am deploying a simple application to PCF and having issues with zuul/eureka/config server. Specific versions used:

Spring Cloud Dependencies: Edgware.SR2
Spring Cloud Services Dependencies (PCF): 1.6.1.RELEASE
Spring Boot Version: 1.5.10.RELEASE

**Issue:**

I have an application.yml with the following content:
```
spring:
  application:
    name: myapp
zuul:
  prefix: /services
  routes: 
   myservice:
     path: /mysvc/**
     url: http://localhost:8081
```

I created **myapp-dev.yml which has overrides for **zuul**

eg: in dev

```
zuul:
  prefix: /services
  routes: 
   myservice:
     path: /mysvc/**
     serviceId: myservice

```

When I see zuul's /env it shows the overridden routes. The issue is when I access the gateway on PCF with a URL like this:

**http://mypcf/services/mysvc** to invoke the mapped controller, the gateway still tries to use the localhost URL from the application.yml instead of serviceId. myservice is the name of the service registered in eureka.

**Comment by sdesa** [comment]
I tried including both the url and serviceId in the route and toggling the **ribbon.eureka.enabled** to **true/false**. That property is not being honored.

```
zuul:
  prefix: /services
  routes: 
   myservice:
     path: /mysvc/**
     serviceId: myservice
     url: http://localhost:8081
```

**Comment by ryanjbaxter** [comment]
Where does `myapp-dev.yml` reside?

**Comment by sdesa** [comment]
In the git-repo that the config server points to. And to narrow down the problem, I put the **serviceId** and **url** in the same **application.yml** and ran the application locally (without eureka running locally) like this below. The flag **ribbon.eureka.enabled** is not being honored. 

So, my application.yml would be: (for the first test

```
zuul:
  prefix: /services
  routes: 
   myservice:
     path: /mysvc/**
     serviceId: myservice
     url: http://localhost:8081

ribbon:
  eureka:
    enabled: false

```

Zuul routes to http://localhost:8081, which is expected behavior.

But when I change the application.yml to disable the flag (in the same application.yml) like this below:

```
zuul:
  prefix: /services
  routes: 
   myservice:
     path: /mysvc/**
     serviceId: myservice
     url: http://localhost:8081

ribbon:
  eureka:
    enabled: true

```

It still works, which is not expected. If eureka is enabled with the flag, shouldn't it fail since it depends on the serviceId (instead of the URL) and I do not have eureka running locally, so there should be nothing found.

**Comment by ryanjbaxter** [comment]
It is not a valid configuration to have both a `serviceId` and `url` specified.  Only one or the other should be present.

**Comment by sdesa** [comment]
Ok, in that case, back to the original question - how do I override the zuul routes so I can make the configuration work locally and when I push to the cloud without having to switch to **serviceId** and **URL** based on where I am working. Shouldn't the config server **serviceId** property override the **URL** property in the **application.yml**?

**Comment by ryanjbaxter** [comment]
I think the best solution is to use profiles and enable a profile when running locally that uses a config file from the config server that contains the local configuration.

**Comment by sdesa** [comment]
Thanks! That is what I was trying to do which I posted in my original post. Sorry if the message was not clear. The dev profile **myapp-dev** is what is used when I push the code to PCF. So, when I check the environment (**/env**), it shows my Zuul routes with the **serviceId** (in the **configService** section), and also shows the **url** down below in the **applicationConfig: [classpath:/application.yml]** section.

When I try to hit the service from Zuul, there is an error in my logs showing that it is trying to connect to **localhost:8081** which is where my service is running. So, the profile override for the Zuul properties is not working. I tried it with the **ribbon.eureka.enabled** property toggle as well, not sure if that is working.

**Comment by ryanjbaxter** [comment]
OK I misunderstood, thanks for clarifying.

Yes its going to merge the configuration together in that case.  What about keeping the configuration in two separate branches, a "dev" branch and a "production" branch?

**Comment by sdesa** [comment]
Yes, that may work too. I was putting URL in **application.yml** so developers on my team do not have to make any changes when running **Zuul** locally. And then when I push to PCF, it picks **serviceId** from the environment profile. I was hoping that Zuul route in the config server would override what the **application.yml** has and use **serviceId** when forwarding to that service. It is not working that way as it merges the Zuul properties (like you mentioned) and tries to go to localhost based on the url when I push to PCF. So, you think the **ribbon.eureka.enabled** will not work in this case and toggle between **true/false** based on application.yml and the yml file in the config server?

Is there a different way to support local development without having to remember to change the **serviceId** to **url** every time I run Zuul locally. I do not use **config server or eureka** locally. They are only bound when I push to PCF.

**Comment by ryanjbaxter** [comment]
I dont think `ribbon.eureka.enabled` will have any effect since that is not going to effect the filter zuul will choose to route the request I dont believe.

If you are not using the config server locally then you can just use the `url` property in your local configuration properties.  When deployed to PCF and using the config server your app should not be using the application configuration in the jar itself, is that not what you are seeing happen?  I was under the impression that you were using the config server locally and on PCF.

**Comment by sdesa** [comment]
"When deployed to PCF and using the config server your app should not be using the application configuration in the jar itself, is that not what you are seeing happen?"

Yes, that is not happening. Zuul is using the application configuration in the jar. It is not using the configuration from the config server based on the profile.

**Comment by sdesa** [comment]
I created 2 sample projects to demonstrate the issue.

**https://github.com/sdesa/simple-gateway**
**https://github.com/sdesa/simple-service**

There are config files in the projects that need to be copied over to the config server.

**Comment by sdesa** [comment]
Sorry for the delay in responding. I created all the additional services required.

https://github.com/sdesa/simple-config-server
https://github.com/sdesa/simple-discovery-server
https://github.com/sdesa/config_files

Created a **dev** profile to override the Zuul URL with the **serviceId** that the service gets registered as. I intentionally set the port in **application.yml** to 7071 to validate that the service gets invoked via the **serviceId** and NOT the **url**.

When I run the service and access the URL 

http://localhost:9090/api/simple

Zuul throws a forwarding error despite the active profile (note the active profile is dev) having a **serviceId** which it should be looking at and NOT the **url** from the application.yml.

So, I believe this seems to be a Zuul bug and not specific to Spring Cloud Services. Hope this clarifies it.

**Comment by ryanjbaxter** [comment]
Since you are only using the config server in PWS I would rename simple-gateway-dev in the config repo to just `simple-gateway`.


The in the `application.yml` of `simple-gateway` change the dev profile section to
```
---
spring:
    profiles: dev

zuul:
  routes:
    simple:   
      url: http://localhost:8081 
```
and activate the dev profile when running locally.  I think this will achieve the functionality you are looking for where in the cloud you would use the `serviceId` (since the dev profile is not activated) but when running locally you would use the `url` since the dev profile is activated.

**Comment by sdesa** [comment]
Thanks Ryan. In theory it should. I will try this out.

**Comment by sdesa** [comment]
This works fine locally, but when pushed to PWS, it does not find the route. Also, if I rename the routes without the dev prefix, I would not be able to differentiate dev, test and prod profiles.

**Comment by ryanjbaxter** [comment]
You are going to have to provide more details, just saying it doesnt work is not very useful.

>  Also, if I rename the routes without the dev prefix, I would not be able to differentiate dev, test and prod profiles.

I never said to rename the routes.

**Comment by sdesa** [comment]
Sorry for the ambiguity. I meant to say, rename the profiles. What you had asked me to do is rename **simple-gateway-dev** to **simple-gateway**. So, all I was saying is, what do I do for the other environments. 

Either way, it did not work. I am confused why adding a flag to Zuul to toggle between URL and serviceId based on discovery **disabled** or **enabled** respectively would not be useful. 

To restate the original problem:

I am defining a Zuul route in **application.yml** with URL (localhost:port) as I am not running discovery locally. When I push the same application to PWS/PCF or even when I run locally with eureka enabled, I want to tell Zuul to use serviceId instead of URL. That is the ask. 

I hoped that I could control the **URL** vs **serviceId** behavior by profiles, which did not work. The repos I created can be used to recreate the behavior locally (without PWS or PCF). If you think it is still confusing, please feel free to close this as a non issue. 

Thanks!

**Comment by ryanjbaxter** [comment]
I dont think your `application.yml` is correct https://github.com/sdesa/simple-gateway/blob/master/src/main/resources/application.yml.

It doesn't make sense that you have the `serviceId` in the default profile.  Here is what my modified `application.yml` looks like
```
spring:
  application:
    name: simple-gateway

#  profiles:
#    active:
#    - dev
    
  cloud:
    config:
      enabled: false   #currently not working, there is an open bug - https://github.com/spring-cloud/spring-cloud-config/issues/829

server:
  port: 9090

zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
    simple:
      path: /simple/**

ribbon: 
  ConnectTimeout: 30000
  ReadTimeout: 10000
  maxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: false
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
            
#disable basic authentication as spring cloud config enables it by default
security:
  basic:
    enabled: false

#disable registering with eureka when running locally    
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
endpoints:
  routes:
    sensitive: false
    
management:
  security:
    enabled: false
    
---
spring:
    profiles: dev

zuul:
  routes:
    simple:   
      url: http://localhost:8081 
```

> So, all I was saying is, what do I do for the other environments.

Well from what I understood from you use case the dev profile was only being used locally and locally you were not using the config server so you wouldnt need a dev profile in the config server.
