### ISSUE TITLE
Yml key cannot contain dot

### ISSUE THREAD

**Issue by GrapeBaBa** [spring-cloud/spring-cloud-config#935]
I have a yml file which contain dot in yml key below, it will understand dot as a separator. Any approach could I use to escape dot?

```yaml
    # Required. list of peers from participating orgs
    peers:
      peer0.hlc.com:
        # [Optional]. will this peer be sent transaction proposals for endorsement? The peer must
        # have the chaincode installed. The app can also use this property to decide which peers
        # to send the chaincode install request. Default: true
        endorsingPeer: true

        # [Optional]. will this peer be sent query proposals? The peer must have the chaincode
        # installed. The app can also use this property to decide which peers to send the
        # chaincode install request. Default: true
        chaincodeQuery: true

        # [Optional]. will this peer be sent query proposals that do not require chaincodes, like
        # queryBlock(), queryTransaction(), etc. Default: true
        ledgerQuery: true

        # [Optional]. will this peer be the target of the SDK's listener registration? All peers can
        # produce events but the app typically only needs to connect to one to listen to events.
        # Default: true
        eventSource: true

```

When request http://localhost:8888/master/xx-xx.yml
it will show like that
```yaml
peers:
      peer0:
            hlc:
              com:
```
