### ISSUE TITLE
Set up multiple ssh keys to access git repository

### ISSUE THREAD

**Issue by babyblue94520** [spring-cloud/spring-cloud-config#938]
I want to set multiple ssh keys to access git repository.
ex:
```yml
spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:team/repo1.git
          private-key: "repo1 rsa private key"
          repos:
            repo2:
              uri: git@github.com:team/repo2.git
              private-key: "repo2 rsa private key"
````
But here is always the last ssh configuration for github.com hostname.
[SshUriPropertyProcessor](https://github.com/spring-cloud/spring-cloud-config/blob/541fbff3521cc9a14b5e8c94f3efe69366dd0e3a/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/ssh/SshUriPropertyProcessor.java)
```java
	private Map<String, SshUri> extractNestedProperties(SshUriProperties uriProperties) {
		Map<String, SshUri> sshUriPropertyMap = new HashMap<>();
		String parentUri = uriProperties.getUri();
		if (isSshUri(parentUri) && getHostname(parentUri) != null) {
			sshUriPropertyMap.put(getHostname(parentUri), uriProperties);
		}
		Map<String, SshUriNestedRepoProperties> repos = uriProperties.getRepos();
		if(repos != null) {
			for (SshUriNestedRepoProperties repoProperties : repos.values()) {
				String repoUri = repoProperties.getUri();
				if (isSshUri(repoUri) && getHostname(repoUri) != null) {
					sshUriPropertyMap.put(getHostname(repoUri), repoProperties);
				}
			}
		}
		return sshUriPropertyMap;
	}
```

And JschConfigSessionFactory only sends github.com host to create session.
[PropertyBasedSshSessionFactory](https://github.com/spring-cloud/spring-cloud-config/blob/18a5da61d445c7042e076e7655c2ed06ec5e7ad6/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/ssh/PropertyBasedSshSessionFactory.java)
```java
	@Override
	protected Session createSession(Host hc, String user, String host, int port, FS fs) throws JSchException {
		if (sshKeysByHostname.containsKey(host)) {
			SshUri sshUriProperties = sshKeysByHostname.get(host);
			jSch.addIdentity(host, sshUriProperties.getPrivateKey().getBytes(), null, null);
			if (sshUriProperties.getKnownHostsFile() != null) {
				jSch.setKnownHosts(sshUriProperties.getKnownHostsFile());
			}
			if (sshUriProperties.getHostKey() != null) {
				HostKey hostkey = new HostKey(host, Base64.decode(sshUriProperties.getHostKey()));
				jSch.getHostKeyRepository().add(hostkey, null);
			}
			return jSch.getSession(user, host, port);
		}
		throw new JSchException("no keys configured for hostname " + host);
	}
```

**Comment by ryanjbaxter** [comment]
If the host names were different than the problem would not exit right?

**Comment by babyblue94520** [comment]
This is an example of the issue.
https://github.com/babyblue94520/config-server-issue

**Comment by ryanjbaxter** [comment]
You have two issues in the repo.  Issue number 1 looks like it was fixed here #892.  I will backport that fix to the 1.4.x stream so it will be in the next Edgware release.

I dont know if we can solve the problem you have described here.  `JschConfigSessionFactory` operates based on host, it doesnt look like it supports separate keys for the same host.  The API doesnt seem to support it.  @ojhughes any thoughts?

**Comment by ryanjbaxter** [comment]
I applied #892 to the 1.4.x branch https://github.com/spring-cloud/spring-cloud-config/commit/dbccf9e5351f138e2c055f909ca1683844ad1e84

**Comment by ojhughes** [comment]
I agree @ryanjbaxter in both cases the Map key is `github.com` so there is a single entry.  Perhaps using the full URL as the Map key would solve this?

**Comment by ryanjbaxter** [comment]
@ojhughes it probably would but the `JschConfigSessionFactory` API is kind of limiting.  The `createSession` API only takes in user, host, port.
`createSession(Host hc, String user, String host, int port, FS fs)`

**Comment by babyblue94520** [comment]
The full URL as a Map key can solve the problem, but JschConfigSessionFactory must be modified,
 although not a good method.
Ex:
https://github.com/babyblue94520/config-server-issue

**Comment by ojhughes** [comment]
The cleanest solution I can think is changing the type of `sshKeysByHostname` to `Map<String, List<SshUri>>` and generate the map using something like `repos.values().stream()							  .collect(Collectors.groupingBy(sshUri -> sshUri.getHostname(repoUri))`

**Comment by ryanjbaxter** [comment]
@ojhughes bump

**Comment by ojhughes** [comment]
This is next on my todo list, will pick up after Easter break next week

**Comment by ojhughes** [comment]
@babyblue94520 I have looked again at this and I think using `composite` configuration is the best way to define multiple repo's with different key's. eg

```
 cloud:
    config:
      server:
        composite:
        -
          type: git
          uri: git@github.com:team/repo1.git
          privateKey: ....
       -
          type: git
          uri: git@github.com:team/repo2.git
          privateKey: ....
```

Currently there is an issue with this approach, see #976  but I think it is better to use the Composite method rather than complicating the existing SSH key handling
