### ISSUE TITLE
If git.uri is ssh uri, then all git.repos must be ssh uri?

### ISSUE THREAD

**Issue by babyblue94520** [spring-cloud/spring-cloud-config#939]
I set git.url to ssh uri, then git.repos cannot set up a normal git repository.
It will have exceptions.
ex:
```yml
spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:team/repo1.git
          private-key: "repo1 rsa private key"
          repos:
            # Reason: Property 'spring.cloud.config.server.git.privateKey' must be set when 'spring.cloud.config.server.git.ignoreLocalSshSettings' is specified
            repo2:
              uri: https://github.com/team/repo2.git
```

I found it was caused by sshUriProperties.isIgnoreLocalSshSettings() .
[HostKeyAlgoSupportedValidator](https://github.com/spring-cloud/spring-cloud-config/blob/541fbff3521cc9a14b5e8c94f3efe69366dd0e3a/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/ssh/HostKeyAlgoSupportedValidator.java)
```java
	@Override
	public boolean isValid(SshUriProperties sshUriProperties, ConstraintValidatorContext context) {
		context.disableDefaultConstraintViolation();
		Set<Boolean> validationResults = new HashSet<>();
		List<SshUri> extractedProperties = sshPropertyValidator.extractRepoProperties(sshUriProperties);
		for (SshUri extractedProperty : extractedProperties) {
			if (sshUriProperties.isIgnoreLocalSshSettings() && isSshUri(extractedProperty.getUri())) {
				validationResults.add(isHostKeySpecifiedWhenAlgorithmSet(extractedProperty, context));
			}
		}
		return !validationResults.contains(false);
	}
```
