### ISSUE TITLE
how to change property value dynamically using spring boot client with config server with Git 

### ISSUE THREAD

**Issue by karanam35** [spring-cloud/spring-cloud-config#957]
My micro service gets notified about some changes of its configuration from the central conf server. It can be partial update, or a full. I use @RefreshScope mark on relevant beans. The question is how to do dynamic refresh of any property value in the bootstrap.yml using with $ for example I am reading value from git that looks like below : 
application.ssl.truststore

I am developing one spring boot client which reads from from GIT through spring config server , When I start my spring boot cleint it will load all the properties from the GIT through GIT. To make Dynamic refresh to the properties I have used @RefreshScope at bean or component level where ever i use @Value annotation, this works fine after i do POST http://<host>:<port>/refresh for my client . I dont have any issues with that . Now my scenario is I am reading some values through client bootstrap.yml file , below is configuration 

client bootstrap.yml: 

	health-check-interval: ${consul.discovery.health.check.interval} 
        scheme: ${consul.discovery.scheme}
        register-health-check: ${consul.discovery.register.health.check}
		
Git configuration :
consul.discovery.health.check.interval=30s
consul.discovery.scheme=http
consul.discovery.register.health.check=true

spring.datasource.url=jdbc:oracle:thin:@host:1521:serviceid
spring.datasource.username=username
spring.datasource.password=password
spring.datasource.driver-class=oracle.jdbc.driver.OracleDriver

Now I want to change property consul.discovery.register.health.check value from http to https dynamically with out restarting the spring boot cleint application, like how I did using @RefreshScope with @Value annotation.

In the same way i want change Data base properties as well. 

Note :the flow is  spring boot client ----> spring config server ---->git repo 

any help would be appreciate !!!!

**Comment by ryanjbaxter** [comment]
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

Why do those properties need to be in `bootstrap.yml` why cant they reside in `application.yml`?

**Comment by karanam35** [comment]
I am integrating with consul so i need to get some properties from the config server so i have used bootstrap.yml .  I have basic knowledge on differences between them, bootstrap.yml is loaded before application.yml.

**Comment by ryanjbaxter** [comment]
```
consul.discovery.health.check.interval=30s
consul.discovery.scheme=http
consul.discovery.register.health.check=true
```
are these located in your Git repo?  If so why do you have the same configuration in `bootstrap.yml` and in the configuration for the app in the Git repo?

**Comment by karanam35** [comment]
Hi ryanjbaxter,
yes the above configuration is there in the GIT repo.

```
Git configuration :
consul.discovery.health.check.interval=30s
consul.discovery.scheme=http
consul.discovery.register.health.check=true
```
below is my boot configuration in my boostrap.yml
```
spring:
  application:
    name: my-app
  cloud:
   consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
         health-check-interval: ${consul.discovery.health.check.interval} 
         scheme: ${consul.discovery.scheme}
        register-health-check: ${consul.discovery.register.health.check}
config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-server
```
we are developing multiple boot services , and we are going for config server with service-id not thru uri. So we need consul properties in my bootstrap.yml.  I am trying to change from http to https from GIT repo, but this change is reflecting even though i did POST /refresh   for my boot client.

Thanks.

**Comment by karanam35** [comment]
Hi ryanjbaxter,
yes the above configuration is there in the GIT repo.

Git configuration :
```
consul.discovery.health.check.interval=30s
consul.discovery.scheme=http
consul.discovery.register.health.check=true
```
below is my boot configuration in my boostrap.yml
```
spring:
  application:
    name: my-app
  cloud:
   consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
         health-check-interval: ${consul.discovery.health.check.interval} 
         scheme: ${consul.discovery.scheme}
        register-health-check: ${consul.discovery.register.health.check}
config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-server
```
we are developing multiple boot services , and we are going for config server with service-id not thru uri. So we need consul properties in my bootstrap.yml. I am trying to change from http to https from GIT repo, but this change is not reflecting even though i did POST /refresh for my boot client.

Thanks.
