### ISSUE TITLE
Cloud Config client not support kubernetes DNS names

### ISSUE THREAD

**Issue by lukaszpy** [spring-cloud/spring-cloud-config#973]
Hi,

On my kubernetes cluster I have simple Service definition which exposing Cloud config Service using DNS names as:
- configuration
- configuration.default.svc.cluster.local
and on port for example: 8866
when I try to run second micor-service with configuration:

```
spring:
  application:
      name: name-discovery
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  cloud:
    config:
      label: ${CONFIG:master}
      fail-fast: true
      uri: ${CONFIG_SERVER:http://localhost:8866}
```

where paramter CONFIG_SERVER is **configuration:8866** I'm getting:

Caused by: java.lang.IllegalStateException: **Invalid URL: configuration:8866**
        at org.springframework.cloud.config.client.ConfigClientProperties.extractCredentials(ConfigClientProperties.java:258) ~[spring-cloud-config-client-2.0.0.M9.jar!/:2.0.0.M9]
        at org.springframework.cloud.config.client.ConfigClientProperties.getPassword(ConfigClientProperties.java:170) ~[spring-cloud-config-client-2.0.0.M9.jar!/:2.0.0.M9]
        ... 23 common frames omitted

which make sens, because there is no protocol in my url.
is there any way to support config service with cubernetes DNS names ?
