### ISSUE TITLE
Support http proxy configuration for git and vault

### ISSUE THREAD

**Issue by pivotal-dylan-roberts** [spring-cloud/spring-cloud-config#992]
The SCS team is hoping to implement this in OSS. 
We could add configuration properties similar to the ones shown below.
This is how it's presently implemented in SCS.
As you can see we'd support separate and distinct http and https proxies for each environment repo of type git or vault. Just vault examples below, obviously.

```
spring.cloud.config.server.vault.proxy:
  http:
    host: ...
    port: ...
    nonProxyHosts: ...
    username: ...
    password: ...
  https:
    host: ...
    port: ...
...
```

or for composite...

```
spring.cloud.config.server:
  composite:
  - type: vault
    proxy:
      http:
        host: ...
        port: ...
 ...
```
